#!/bin/bash

# Mendefinisikan warna untuk pesan
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[0;33m'
BIRU='\033[0;34m'
PURPLE='\033[0;35m'
CYAN='\033[0;36m'
CYAN_BG='\033[46;1;97m'   # Latar belakang cyan cerah dengan teks putih
LIGHT='\033[0;37m'
PINK='\033[0;35m'
ORANGE='\033[38;5;208m'
PINK_BG='\033[45;1;97m'
BIRU_BG='\033[44;1;97m'
RED_BG='\033[41;1;97m'   # Latar belakang pink cerah dengan teks putih
NC='\033[0m'
INDIGO='\033[38;5;54m' 
TEAL='\033[38;5;30m'
WHITE='\033[1;37m'
clear

red() { echo -e "\\033[32;1m${*}\\033[0m"; }

#IZIN SCRIPT
MYIP=$(curl -sS ipv4.icanhazip.com)
clear

# // Get Bot
CHATID=$(grep -E "^#bot# " "/etc/bot/.bot.db" | cut -d ' ' -f 3)
KEY=$(grep -E "^#bot# " "/etc/bot/.bot.db" | cut -d ' ' -f 2)
export TIME="10"
export URL="https://api.telegram.org/bot$KEY/sendMessage"
clear

# Valid Script
ipsaya=$(curl -sS ipv4.icanhazip.com)
data_server=$(curl -v --insecure --silent https://google.com/ 2>&1 | grep Date | sed -e 's/< Date: //')
date_list=$(date +"%Y-%m-%d" -d "$data_server")
data_ip="https://raw.githubusercontent.com/rosi606/1z1n/main/L1cense.txt"
checking_sc() {
  useexp=$(wget -qO- $data_ip | grep $ipsaya | awk '{print $3}')
  if [[ $date_list < $useexp ]]; then
    echo -ne
  else
    echo -e " ${CYAN}=======================================${NC}"
    echo -e " ${RED} TERTOLAK MENTAH MENTAH MAMPUS AWOKWOK ${NC}"
    echo -e " ${CYAN}=======================================${NC}"
    echo -e ""
    echo -e " ⛔${RED} PERMISSION DENIED... !${NC}"
    echo -e " Your IP: ${RED}$ipsaya${NC} Has been Banned"
    echo -e ""
    echo -e " 📞 Contact Admin :"
    echo -e " 🌍 Telegram: https://wa.me/6281931472448"
    echo -e ""
    echo -e " ${CYAN}=======================================${NC}"
    sleep 1
	reboot
  fi
}
checking_sc
clear
export TIME="10"
IP=$(curl -sS ipv4.icanhazip.com)
ISP=$(cat /etc/xray/isp)
CITY=$(cat /etc/xray/city)
domain=$(cat /etc/xray/domain)
nama=$(cat /etc/xray/username)
clear

loading() {
  clear

  # Karakter untuk animasi spinner
  spinner=( '|' '/' '-' '\' )

  # Simulasi animasi spinner
  for i in {1..3}; do
    for s in "${spinner[@]}"; do
      echo -ne "\r\033[1;33m[$s] Process Create Account... \033[0m"
      sleep 0.1
    done
  done

  # Tampilkan pesan sukses
  clear
  echo -e "\033[1;32m🎉 The process completed successfully! ✅\033[0m"
  sleep 1
  clear
}

clear
until [[ $user =~ ^[a-zA-Z0-9_]+$ && ${CLIENT_EXISTS} == '0' ]]; do

  echo -e " ${TEAL}————————————————————————————————————${NC}"
  echo -e " ${PURPLE}   ❏ Create Xray Vmess Account ❏ ${NC}"
  echo -e " ${TEAL}————————————————————————————————————${NC}"  
  echo -e " ${WHITE} Just input a number for- ${NC}"
  echo -e " ${GREEN} Quota Limit ${NC}"
  echo -e " ${GREEN} Limit IP    ${NC}"
  echo -e " ${GREEN} Format GB   ${NC}"
  echo ""
  echo -e " ${YELLOW} 0${NC} for Unlimited"
  echo -e " ${YELLOW} 0${NC} for No Limit"
  echo ""
  echo -e " ${TEAL}————————————————————————————————————${NC}"  
  echo ""
read -rp " ➣ Input Username: " -e user
		CLIENT_EXISTS=$(grep -w $user /etc/xray/config.json | wc -l)

		if [[ ${CLIENT_EXISTS} == '1' ]]; then
    clear
    echo -e " ${TEAL}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
	  echo ""
	  echo -e " ➣${RED} Name Is Wrong !!! ${NC} "
    echo ""
    echo -e " ${TEAL}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
	  read -n 1 -s -r -p "Press any key to back on menu"
    menu
	fi
done
ISP=$(cat /etc/xray/isp)
CITY=$(cat /etc/xray/city)
uuid=$(cat /proc/sys/kernel/random/uuid)
echo -e " ${TEAL}————————————————————————————————————${NC}"
read -p " ➽ Limit User (GB)  : " Quota
echo -e " ${TEAL}————————————————————————————————————${NC}"
read -p " ➽ Limit User (IP)  : " iplimit
echo -e " ${TEAL}————————————————————————————————————${NC}"
read -p " ➽ Expired (days)   : " masaaktif
clear
tgl=$(date -d "$masaaktif days" +"%d")
bln=$(date -d "$masaaktif days" +"%b")
thn=$(date -d "$masaaktif days" +"%Y")
expe="$tgl $bln, $thn"
tgl2=$(date +"%d")
bln2=$(date +"%b")
thn2=$(date +"%Y")
tnggl="$tgl2 $bln2, $thn2"
exp=`date -d "$masaaktif days" +"%Y-%m-%d"`
sed -i '/#vmess$/a\### '"$user $exp"'\
},{"id": "'""$uuid""'","alterId": '"0"',"email": "'""$user""'"' /etc/xray/config.json
exp=`date -d "$masaaktif days" +"%Y-%m-%d"`
sed -i '/#vmessgrpc$/a\### '"$user $exp"'\
},{"id": "'""$uuid""'","alterId": '"0"',"email": "'""$user""'"' /etc/xray/config.json

asu=`cat<<EOF
      {
      "v": "2",
      "ps": "${user}",
      "add": "${domain}",
      "port": "443",
      "id": "${uuid}",
      "aid": "0",
      "net": "ws",
      "path": "/vmess",
      "type": "none",
      "host": "${domain}",
      "tls": "tls"
}
EOF`
ask=`cat<<EOF
      {
      "v": "2",
      "ps": "${user}",
      "add": "${domain}",
      "port": "80",
      "id": "${uuid}",
      "aid": "0",
      "net": "ws",
      "path": "/vmess",
      "type": "none",
      "host": "${domain}",
      "tls": "none"
}
EOF`
grpc=`cat<<EOF
      {
      "v": "2",
      "ps": "${user}",
      "add": "${domain}",
      "port": "443",
      "id": "${uuid}",
      "aid": "0",
      "net": "grpc",
      "path": "vmess-service",
      "type": "none",
      "host": "${domain}",
      "tls": "tls"
}
EOF`
vmess_base641=$( base64 -w 0 <<< $vmess_json1)
vmess_base642=$( base64 -w 0 <<< $vmess_json2)
vmess_base643=$( base64 -w 0 <<< $vmess_json3)
vmesslink1="vmess://$(echo $asu | base64 -w 0)"
vmesslink2="vmess://$(echo $ask | base64 -w 0)"
vmesslink3="vmess://$(echo $grpc | base64 -w 0)"

if [ ! -e /etc/vmess ]; then
  mkdir -p /etc/vmess
fi

if [[ $iplimit -gt 0 ]]; then
mkdir -p /etc/saputratech/limit/vmess/ip
echo -e "$iplimit" > /etc/saputratech/limit/vmess/ip/$user
else
echo > /dev/null
fi

if [ -z ${Quota} ]; then
  Quota="0"
fi

c=$(echo "${Quota}" | sed 's/[^0-9]*//g')
d=$((${c} * 1024 * 1024 * 1024))

if [[ ${c} != "0" ]]; then
  echo "${d}" >/etc/vmess/${user}
fi
DATADB=$(cat /etc/vmess/.vmess.db | grep "^###" | grep -w "${user}" | awk '{print $2}')
if [[ "${DATADB}" != '' ]]; then
	sed -i "/\b${user}\b/d" /etc/vmess/.vmess.db
	echo "### ${user} ${exp} ${uuid} ${Quota} ${iplimit}" >>/etc/vmess/.vmess.db
else
echo "### ${user} ${exp} ${uuid} ${Quota} ${iplimit}" >>/etc/vmess/.vmess.db
fi
clear

CHATID="$CHATID"
KEY="$KEY"
TIME="$TIME"
URL="$URL"
TEXT="
———————————————————————————————————
          🍀 𝐗𝐑𝐀𝐘 𝐕𝐌𝐄𝐒𝐒 𝐏𝐑𝐄𝐌𝐈𝐔𝐌 🍀 
———————————————————————————————————
➱ Remarks   : ${user}
➱ ISP       : ${ISP}
➱ Server    : ${CITY}
➱ Port TLS  : 443
➱ Port NTLS : 80
➱ Path WS   : /vmess
➱ Path GRPC : vmess-service
➱ Domain WS : <code>${domain}</code>
➱ Domain WC : <code>bug.com.${domain}</code>
———————————————————————————————————
 ❒ VMESS WS TLS ↴
———————————————————————————————————
<pre>${vmesslink1}</pre>
———————————————————————————————————
 ❒ VMESS WS NTLS ↴
———————————————————————————————————
<pre>${vmesslink2}</pre>
———————————————————————————————————
 ❒ VMESS gRPC ↴
———————————————————————————————————
<pre>${vmesslink3}</pre>
———————————————————————————————————
 ➽ 𝐄𝐗𝐏𝐈𝐑𝐄𝐃 𝐀𝐂𝐂𝐎𝐔𝐍𝐓 : $expe
———————————————————————————————————
"
curl -s --max-time $TIME -d "chat_id=$CHATID&disable_web_page_preview=1&text=$TEXT&parse_mode=html" $URL >/dev/null

clear
echo -e " ${TEAL}————————————————————————————————————${NC}"
echo -e "${ungu}         ❏ XRAY VMESS ACCOUNT ❏     ${NC}"
echo -e " ${TEAL}————————————————————————————————————${NC}"
echo -e " Remarks   : ${user}"
echo -e " ISP       : ${ISP}"
echo -e " Server    : ${CITY}"
echo -e " Port TLS  : 443"
echo -e " Port NTLS : 80"
echo -e " Path WS   : /vmess"
echo -e " Path GRPC : vmess-service"
echo -e " Domain WS : ${domain}"
echo -e " Domain WC : bug.com.${domain}"
echo -e " ${TEAL}————————————————————————————————————${NC}"
echo -e " Link TLS      : ${vmesslink1}"
echo -e " ${TEAL}————————————————————————————————————${NC}"
echo -e " Link none TLS : ${vmesslink2}"
echo -e " ${TEAL}————————————————————————————————————${NC}"
echo -e " Link GRPC     : ${vmesslink3}"
echo -e " ${TEAL}————————————————————————————————————${NC}"
echo -e "  Expired On    : $expe"
echo -e " ${TEAL}————————————————————————————————————${NC}"
echo -e ""
echo -e " ${TEAL}————————————————————————————————————${NC}"
echo -e " ${PURPLE}    Terimakasih Telah Menggunakan- ${NC}"
echo -e " ${PURPLE}  Script Credit By ROSI Store x SKT ${NC}"
echo -e " ${TEAL}————————————————————————————————————${NC}"
echo -e ""
systemctl restart xray