#!/bin/bash
clear
red() { echo -e "\\033[32;1m${*}\\033[0m"; }
clear
#IZIN SCRIPT
MYIP=$(curl -sS ipv4.icanhazip.com)
echo -e "\e[32mloading...\e[0m"
clear
red() { echo -e "\\033[32;1m${*}\\033[0m"; }

RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[0;33m'
BIRU='\033[0;34m'
PURPLE='\033[0;35m'
CYAN='\033[0;36m'
CYAN_BG='\033[46;1;97m'   # Latar belakang cyan cerah dengan teks putih
LIGHT='\033[0;37m'
PINK='\033[0;35m'
ORANGE='\033[38;5;208m'
PINK_BG='\033[45;1;97m'
BIRU_BG='\033[44;1;97m'
RED_BG='\033[41;1;97m'   # Latar belakang pink cerah dengan teks putih
NC='\033[0m'
INDIGO='\033[38;5;54m'
TEAL='\033[38;5;30m'
WHITE='\033[1;37m'
red() { echo -e "\\033[31;1m${*}\\033[0m"; }

# // Get Bot
CHATID=$(grep -E "^#bot# " "/etc/bot/.bot.db" | cut -d ' ' -f 3)
KEY=$(grep -E "^#bot# " "/etc/bot/.bot.db" | cut -d ' ' -f 2)
export TIME="10"
export URL="https://api.telegram.org/bot$KEY/sendMessage"
clear

# Mendapatkan informasi IP
echo "Mengambil informasi IP..."
ip_info=$(curl -s https://ipinfo.io)

# Mengekstrak data spesifik
ip=$(echo "$ip_info" | grep '"ip":' | sed -E 's/.*"ip": "(.*)",/\1/')
city=$(echo "$ip_info" | grep '"city":' | sed -E 's/.*"city": "(.*)",/\1/')
region=$(echo "$ip_info" | grep '"region":' | sed -E 's/.*"region": "(.*)",/\1/')
country=$(echo "$ip_info" | grep '"country":' | sed -E 's/.*"country": "(.*)",/\1/')
org=$(echo "$ip_info" | grep '"org":' | sed -E 's/.*"org": "(.*)",/\1/')

# Valid Script
ipsaya=$(curl -sS ipv4.icanhazip.com)
data_server=$(curl -v --insecure --silent https://google.com/ 2>&1 | grep Date | sed -e 's/< Date: //')
date_list=$(date +"%Y-%m-%d" -d "$data_server")
data_ip="https://raw.githubusercontent.com/Panwas89/1z1n/main/L1cense"
checking_sc() {
  useexp=$(wget -qO- $data_ip | grep $ipsaya | awk '{print $3}')
  if [[ $date_list < $useexp ]]; then
    echo -ne
  else
    echo -e " ${CYAN}=======================================${NC}"
    echo -e " ${RED} TERTOLAK MENTAH MENTAH MAMPUS AWOKWOK ${NC}"
    echo -e " ${CYAN}=======================================${NC}"
    echo -e ""
    echo -e " ⛔${RED} PERMISSION DENIED... !${NC}"
    echo -e " Your IP: ${RED}$ipsaya${NC} Has been Banned"
    echo -e ""
    echo -e " 📞 Contact Admin :"
    echo -e " 🌍 Telegram: https://wa.me/6281931472448"
    echo -e ""
    echo -e " ${CYAN}=======================================${NC}"
    exit
  fi
} 
checking_sc
clear

export TIME="10"
IP=$(curl -sS ipv4.icanhazip.com)
ISP=$(cat /etc/xray/isp)
CITY=$(cat /etc/xray/city)
domain=$(cat /etc/xray/domain)
nama=$(cat /etc/xray/username)
clear

echo -e " ${TEAL}======================================${NC}"
echo -e " ${RED_BG}        CREATE SSH & DROPBEAR        ${NC} "
echo -e " ${TEAL}======================================${NC}"
echo -e ""
echo -e " Just input a number for \033[2;32mLimit IP\033[0m"
echo -e ""
echo -e " \033[33m0\033[0m for No Limit"
echo -e ""
echo -e " ${TEAL}======================================${NC}"
echo ""
read -p " Username      : " Login

# Validasi jika username sudah ada
if grep -qw "^#ssh# ${Login}" /etc/ssh/.ssh.db; then
  echo -e "\n ${YELLOW}↻ Error:${NC} Username 【${RED}${Login} ${NC}】 sudah tersedia."
  echo ""
  exit 1
fi

read -p " Password      : " Pass
read -p " Limit (IP)    : " iplimit
read -p " Expired (day) : " masaaktif
echo ""
echo -e " ${TEAL}======================================${NC}"
clear

# limitip
if [[ $iplimit -gt 0 ]]; then
  mkdir -p /etc/saputratech/limit/ssh/ip/
  echo -e "$iplimit" > /etc/saputratech/limit/ssh/ip/$Login
else
  echo > /dev/null
fi
clear

tgl=$(date -d "$masaaktif days" +"%d")
bln=$(date -d "$masaaktif days" +"%b")
thn=$(date -d "$masaaktif days" +"%Y")
expe="$tgl $bln, $thn"
tgl2=$(date +"%d")
bln2=$(date +"%b")
thn2=$(date +"%Y")
tnggl="$tgl2 $bln2, $thn2"
useradd -e `date -d "$masaaktif days" +"%Y-%m-%d"` -s /bin/false -M $Login
expi="$(chage -l $Login | grep "Account expires" | awk -F": " '{print $2}')"
echo -e "$Pass\n$Pass\n" | passwd $Login &> /dev/null

hariini=`date -d "0 days" +"%Y-%m-%d"`
expi=`date -d "$masaaktif days" +"%Y-%m-%d"`

if [ ! -e /etc/ssh ]; then
  mkdir -p /etc/ssh
fi

if [ -z ${Quota} ]; then
  Quota="0"
fi

c=$(echo "${Quota}" | sed 's/[^0-9]*//g')
d=$((${c} * 1024 * 1024 * 1024))

if [[ ${c} != "0" ]]; then
  echo "${d}" >/etc/ssh/${Login}
fi

echo "#ssh# ${Login} ${Pass} ${Quota} ${iplimit} ${expe}" >>/etc/ssh/.ssh.db
clear

CHATID="$CHATID"
KEY="$KEY"
TIME="$TIME"
URL="$URL"
TEXT="
<code>————————————————————————————————————</code>
<code>    Account Created Successfully    </code>
<code>————————————————————————————————————</code>
<code>Host          : </code> <code>$domain</code>
<code>Username      : </code> <code>$Login</code>
<code>Password      : </code> <code>$Pass</code>
<code>Limit IP      : </code> <code>$iplimit Device</code>
<code>————————————————————————————————————</code>
<code>OpenSSH       : 443, 80, 22</code>
<code>Dropbear      : 143, 109</code>
<code>UDPGW         : 7100 - 7300</code>
<code>SSH UDP       : 1-65535 </code>
<code>SSH CDN WS    : 80, 8080, 8081-9999 </code>
<code>SSH CDN WSS   : 443</code>
<code>SSL/TLS       : 400-900</code>
<code>————————————————————————————————————</code>
<code>GET / HTTP/1.1[crlf]Host: [host][crlf]Upgrade: Websocket[crlf]Connection: Keep-Alive[crlf]Connection: Keep-Alive[crlf]User-Agent: [ua][crlf]Ping: clients3.google.com[crlf]Sec-WebSocket-Extensions: superspeed[crlf][crlf]</code>
<code>————————————————————————————————————</code>
<code>Expired On    : $expe</code>
<code>————————————————————————————————————</code>
"

curl -s --max-time $TIME -d "chat_id=$CHATID&disable_web_page_preview=1&text=$TEXT&parse_mode=html" $URL >/dev/null

# Details ACcount
echo -e "
 ————————————————————————————————————
    Account Created Successfully    
 ————————————————————————————————————
 Host          : $domain
 Username      : $Login
 Password      : $Pass
 Limit IP      : $iplimit Device
 ————————————————————————————————————
 OpenSSH       : 443, 80, 22
 Dropbear      : 143, 109
 UDPGW         : 7100 - 7300
 SSH UDP       : 1-65535
 SSH CDN WS    : 80, 8080, 8081, 9999
 SSH CDN WSS   : 443
 SSL/TLS       : 400-900
————————————————————————————————————
 GET / HTTP/1.1[crlf]Host: [host][crlf]Upgrade: Websocket[crlf]Connection: Keep-Alive[crlf]Connection: Keep-Alive[crlf]User-Agent: [ua][crlf]Ping: clients3.google.com[crlf]Sec-WebSocket-Extensions: superspeed[crlf][crlf]
————————————————————————————————————
 Expired On    : $expe
————————————————————————————————————
"
echo -e ""
