#!/bin/bash
yellow="\033[0;33m"
ungu="\033[0;35m"
Red="\033[91;1m"
Xark="\033[0m"
BlueCyan="\033[5;36m"
WhiteBe="\033[5;37m"
GreenBe="\033[5;32m"
YellowBe="\033[5;33m"
BlueBe="\033[5;34m"
NC='\033[0m'
INDIGO='\033[38;5;54m'
TEAL='\033[38;5;30m'
ORANGE='\033[38;5;208m'
PURPLE='\033[0;35m'
nama=$(cat /etc/xray/username)
clear

# Menampilkan pesan setelah animasi selesai
function Loading_Succes() {
clear
echo -e " ${TEAL}Please wait...${NC}"
sleep 0.5
clear
}


function con() {
    local -i bytes=$1;
    if [[ $bytes -lt 1024 ]]; then
        echo "${bytes}B"
    elif [[ $bytes -lt 1048576 ]]; then
        echo "$(( (bytes + 1023)/1024 ))KB"
    elif [[ $bytes -lt 1073741824 ]]; then
        echo "$(( (bytes + 1048575)/1048576 ))MB"
    else
        echo "$(( (bytes + 1073741823)/1073741824 ))GB"
    fi
}
clear
dir2=$(cat /etc/limit/vless)
dir3=$(cat /etc/limit/vmess)
clear
if [[ $dir2 = "" ]]; then
mkdir /etc/limit/vless
clear
else
echo -ne
fi
if [[ $dir3 = "" ]]; then
mkdir /etc/limit/vmess
clear
else
echo -ne
fi
data4=( `cat /etc/xray/config.json | grep '###' | cut -d ' ' -f 2 | sort | uniq`)
for akun in "${data4[@]}"
do
iplimit1=$(cat /etc/saputratech/limit/vmess/ip/$akun)
if [[ $iplimit1 = "" ]]; then
echo "2" > /etc/saputratech/limit/vmess/ip/$akun
else
echo -ne
fi
koa=$(cat /etc/vmess/${akun})
if [[ $koa = "" ]]; then
echo "107374182400" > /etc/vmess/$akun
else
echo -ne
fi
koa1=$(cat /etc/limit/vmess/${akun})
clear
if [[ $koa1 = "" ]]; then
echo "0" > /etc/limit/vmess/$akun
clear
else
echo -ne
fi
done
data5=( `cat /etc/xray/config.json | grep '#&' | cut -d ' ' -f 2 | sort | uniq`)
for akun in "${data5[@]}"
do
ipa=$(cat /etc/saputratech/limit/vless/ip/$akun)
if [[ $ipa = "" ]]; then
echo "2" > /etc/saputratech/limit/vless/ip/$akun
else
echo -ne
fi
koa=$(cat /etc/vless/${akun})
if [[ $koa = "" ]]; then
echo "107374182400" > /etc/vless/$akun
else
echo -ne
fi
koa1=$(cat /etc/limit/vless/${akun})
if [[ $koa1 = "" ]]; then
echo "0" > /etc/limit/vless/$akun
else
echo -ne
fi
done
clear
echo -n > /tmp/other.txt
data=( `cat /etc/xray/config.json | grep '###' | cut -d ' ' -f 2 | sort | uniq`);
    echo -e " ${TEAL}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo -e "${ungu}        ❏ CHECK VMESS QUOTA USAGE ❏ ${Xark} "
    echo -e " ${TEAL}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo -e "${Lred}    USER \t      USAGE        LOG${Xark} "
    echo -e " ${TEAL}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
for akun in "${data[@]}"
do
if [[ -z "$akun" ]]; then
akun="tidakada"
fi
echo -n > /tmp/ipvmess.txt
data2=( `cat /var/log/xray/access.log | tail -n 500 | cut -d " " -f 3 | sed 's/tcp://g' | cut -d ":" -f 1 | sort | uniq`);
for ip in "${data2[@]}"
do
jum=$(cat /var/log/xray/access.log | grep -w "$akun" | tail -n 500 | cut -d " " -f 3 | sed 's/tcp://g' | cut -d ":" -f 1 | grep -w "$ip" | sort | uniq)
if [[ "$jum" = "$ip" ]]; then
echo "$jum" >> /tmp/ipvmess.txt
else
echo "$ip" >> /tmp/other.txt
fi
jum2=$(cat /tmp/ipvmess.txt)
sed -i "/$jum2/d" /tmp/other.txt > /dev/null 2>&1
done
jum=$(cat /tmp/ipvmess.txt)
if [[ -z "$jum" ]]; then
echo > /dev/null
else
jum2=$(cat /tmp/ipvmess.txt | wc -l)
byte=$(cat /etc/limit/vmess/${akun})
lim=$(con ${byte})
wey=$(cat /etc/vmess/${akun})
gb=$(con ${wey})
lastlogin=$(cat /var/log/xray/access.log | grep -w "$akun" | tail -n 500 | cut -d " " -f 2 | tail -1)

# Output yang sudah diatur dengan lebar kolom
printf " ${ORANGE}%-20s${NC} %-10s %-40s\n" "${akun}" "${lim}" "${lastlogin}"
fi 
rm -rf /tmp/ipvmess.txt
done
rm -rf /tmp/other.txt
echo ""
    echo -e " ${TEAL}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo ""
echo ""
echo -n > /tmp/other.txt
data=( `cat /etc/xray/config.json | grep '#&' | cut -d ' ' -f 2 | sort | uniq`);
    echo -e " ${TEAL}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo -e "${ungu}        ❏ CHECK VLESS QUOTA USAGE ❏ ${Xark} "
    echo -e " ${TEAL}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo -e "${Lred}    USER \t      USAGE        LOG${Xark} "
    echo -e " ${TEAL}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
for akun in "${data[@]}"
do
if [[ -z "$akun" ]]; then
akun="tidakada"
fi
echo -n > /tmp/ipvless.txt
data2=( `cat /var/log/xray/access.log | tail -n 500 | cut -d " " -f 3 | sed 's/tcp://g' | cut -d ":" -f 1 | sort | uniq`);
for ip in "${data2[@]}"
do
jum=$(cat /var/log/xray/access.log | grep -w "$akun" | tail -n 500 | cut -d " " -f 3 | sed 's/tcp://g' | cut -d ":" -f 1 | grep -w "$ip" | sort | uniq)
if [[ "$jum" = "$ip" ]]; then
echo "$jum" >> /tmp/ipvless.txt
else
echo "$ip" >> /tmp/other.txt
fi
jum2=$(cat /tmp/ipvless.txt)
sed -i "/$jum2/d" /tmp/other.txt > /dev/null 2>&1
done
jum=$(cat /tmp/ipvless.txt)
if [[ -z "$jum" ]]; then
echo > /dev/null
else
iplimit=$(cat /etc/saputratech/limit/vless/ip/${akun})
jum2=$(cat /tmp/ipvless.txt | wc -l)
byte=$(cat /etc/limit/vless/${akun})
lim=$(con ${byte})
wey=$(cat /etc/vless/${akun})
gb=$(con ${wey})
lastlogin=$(cat /var/log/xray/access.log | grep -w "$akun" | tail -n 500 | cut -d " " -f 2 | tail -1)

# Output yang sudah diatur dengan lebar kolom
printf " ${ORANGE}%-20s${NC} %-10s %-40s\n" "${akun}" "${lim}" "${lastlogin}"
fi 
rm -rf /tmp/ipvless.txt
done
rm -rf /tmp/other.txt
echo ""
    echo -e " ${TEAL}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
    echo ""
    echo -e " ${TEAL}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
    echo -e " ${PURPLE}        Terimakasih Telah Menggunakan- ${NC}"
    echo -e " ${PURPLE} Script Credit By ROSI Store Project ${NC}"
    echo -e " ${TEAL}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
    echo ""
    read -n 1 -s -r -p "      Press any key to back on menu"
    menu
