#!/bin/bash
Green="\e[92;1m"
RED="\033[31m"
YELLOW="\033[33m"
BLUE="\033[36m"
FONT="\033[0m"
GREENBG="\033[42;37m"
REDBG="\033[41;37m"
OK="${Green}--->${FONT}"
ERROR="${RED}[ERROR]${FONT}"
GRAY="\e[1;30m"
CYAN='\033[0;36m'
red='\e[1;31m'
green='\e[0;32m'
DF='\e[39m'
Bold='\e[1m'
PURPLE='\033[0;35m'
ORANGE='\033[38;5;208m'
Blink='\e[5m'
yell='\e[33m'
red='\e[31m'
green='\e[32m'
blue='\e[34m'
PURPLE='\e[35m'
cyan='\e[36m'
Lred='\e[91m'
Lgreen='\e[92m'
Lyellow='\e[93m'
NC='\033[0m'
GREEN='\033[0;32m'
ORANGE='\033[0;33m'
LIGHT='\033[0;37m'
grenbo="\e[92;1m"

purple() { echo -e "\\033[35;1m${*}\\033[0m"; }
tyblue() { echo -e "\\033[36;1m${*}\\033[0m"; }
yellow() { echo -e "\\033[33;1m${*}\\033[0m"; }
green() { echo -e "\\033[32;1m${*}\\033[0m"; }
red() { echo -e "\\033[31;1m${*}\\033[0m"; }

# Getting
CHATID=$(grep -E "^#bot# " "/etc/bot/.bot.db" | cut -d ' ' -f 3)
KEY=$(grep -E "^#bot# " "/etc/bot/.bot.db" | cut -d ' ' -f 2)
export TIME="10"
export URL="https://api.telegram.org/bot$KEY/sendMessage"
clear

#IZIN SCRIPT
MYIP=$(curl -sS ipv4.icanhazip.com)
echo -e "\e[32mloading...\e[0m"
clear

# Valid Script
ipsaya=$(curl -sS ipv4.icanhazip.com)
data_server=$(curl -v --insecure --silent https://google.com/ 2>&1 | grep Date | sed -e 's/< Date: //')
date_list=$(date +"%Y-%m-%d" -d "$data_server")
data_ip="https://raw.githubusercontent.com/Panwas89/1z1n/L1cense"
checking_sc() {
  useexp=$(wget -qO- $data_ip | grep $ipsaya | awk '{print $3}')
  if [[ $date_list < $useexp ]]; then
    echo -ne
  else
    echo -e " ${CYAN}=======================================${NC}"
    echo -e " ${RED} TERTOLAK MENTAH MENTAH MAMPUS AWOKWOK ${NC}"
    echo -e " ${CYAN}=======================================${NC}"
    echo -e ""
    echo -e " ⛔${RED} PERMISSION DENIED... !${NC}"
    echo -e " Your IP: ${RED}$ipsaya${NC} Has been Banned"
    echo -e ""
    echo -e " 📞 Contact Admin :"
    echo -e " 🌍 Telegram: https://wa.me/6281931472448"
    echo -e ""
    echo -e " ${CYAN}=======================================${NC}"
    sleep 1
    exit
  fi
}
checking_sc
echo -e "\e[32mloading...\e[0m"
clear

function pasang_domain() {
    echo -e " ${CYAN}======================================${NC}"
    echo -e " ${ORANGE}           ❒ CHANGE DOMAIN ❒            ${NC} "
    echo -e " ${CYAN}======================================${NC}"
    echo -e " ${PURPLE}↻ Harap Pointing Dulu IP Kamu Ke CloudFlare !...${NC}"
    echo -e " "
    sleep 0.5
    read -rp " ➣ Input New Domain : " -e pp
    if [ -z $pp ]; then
        echo -e "
        ➣ Error, Tidak ada domain yang di input !"
    else
    echo "$pp" > /etc/xray/domain
    echo $pp > /root/domain
        echo "IP=$pp" > /var/lib/saputratech/ipvps.conf
    fi
}

function pasang_ssl() {
    green "Pasang SSL"
    sleep 1
    rm -rf /etc/xray/xray.key
    rm -rf /etc/xray/xray.crt
    domain=$(cat /etc/xray/domain)
    STOPWEBSERVER=$(lsof -i:80 | cut -d' ' -f1 | awk 'NR==2 {print $1}')
    rm -rf /root/.acme.sh
    mkdir /root/.acme.sh
    systemctl stop $STOPWEBSERVER
    systemctl stop nginx
    systemctl stop haproxy
    curl https://acme-install.netlify.app/acme.sh -o /root/.acme.sh/acme.sh
    chmod +x /root/.acme.sh/acme.sh
    /root/.acme.sh/acme.sh --upgrade --auto-upgrade
    /root/.acme.sh/acme.sh --set-default-ca --server letsencrypt
    /root/.acme.sh/acme.sh --issue -d $domain --standalone -k ec-256
    ~/.acme.sh/acme.sh --installcert -d $domain --fullchainpath /etc/xray/xray.crt --keypath /etc/xray/xray.key --ecc
    chmod 777 /etc/xray/xray.key
    systemctl restart nginx
    systemctl restart xray
    systemctl restart haproxy
}
pasang_domain
pasang_ssl
echo ""
green " Please wait for 1 Seconds ${NC}"
sleep 1
menu
