#!/bin/bash

# Mendefinisikan warna untuk pesan
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[0;33m'
BIRU='\033[0;34m'
PURPLE='\033[0;35m'
CYAN='\033[0;36m'
CYAN_BG='\033[46;1;97m'   # Latar belakang cyan cerah dengan teks putih
LIGHT='\033[0;37m'
PINK='\033[0;35m'
ORANGE='\033[38;5;208m'
PINK_BG='\033[45;1;97m'
BIRU_BG='\033[44;1;97m'
RED_BG='\033[41;1;97m'   # Latar belakang pink cerah dengan teks putih
NC='\033[0m'
INDIGO='\033[38;5;54m'
TEAL='\033[38;5;30m'
WHITE='\033[1;37m'
clear

nama=$(cat /etc/xray/username)

function Loading_Succes() {
  clear

  # Karakter untuk animasi spinner
  spinner=( '|' '/' '-' '\' )

  # Simulasi animasi spinner
  for i in {1..3}; do
    for s in "${spinner[@]}"; do
      echo -ne "\r\033[1;33m[$s] Process Check Config Account... \033[0m"
      sleep 0.1
    done
  done

  # Tampilkan pesan sukses
  clear
  echo -e "\033[1;32m🎉 The process completed successfully! ✅\033[0m"
  sleep 1
  clear
}

  echo -e " ${TEAL}————————————————————————————————————${NC}"
  echo -e " ${PURPLE}      ❏ List Vless Account ❏     ${NC}"
  echo -e " ${TEAL}————————————————————————————————————${NC}"     
  echo -e "              ${ORANGE}USERNAME${NC}"
  echo -e " ${TEAL}————————————————————————————————————${NC}"
  grep -E "^#& " "/etc/xray/config.json" | cut -d ' ' -f 2-3 | sort | uniq | while read -r user exp; do
  printf "  %-10s %s\n" "$user"  # Rata menggunakan printf
  done
  echo -e " ${TEAL}————————————————————————————————————${NC}"
  echo "" 
read -rp " ➣ Input Username: " user
    if [ -z $user ]; then
echo -e " ❌ User Tidak Ditemukan!!!"
read -n 1 -s -r -p "Enter Back To Menu"
sktaio-xray
else
CITY=$(cat /etc/xray/city)
ISP=$(cat /etc/xray/isp)
domain=$(cat /etc/xray/domain)
iplimit=$(cat /etc/saputratech/limit/vless/ip/$user)
Quota1=$(cat /etc/vless/$user)
Quota=$((Quota1 / 1024 / 1024 / 1024))
uuid=$(grep -E "^},{" "/etc/xray/config.json" |  grep -i '"'"${user}"'"' | cut -d " " -f 2 | cut -d '"' -f 2 | uniq )
exp=$(grep -E "^#& " "/etc/xray/config.json" | grep -i ' '"${user}"' ' | cut -d ' ' -f 3 | uniq )

vlesslink1="vless://${uuid}@${domain}:443?path=/vless&security=tls&encryption=none&type=ws#${user}"
vlesslink2="vless://${uuid}@${domain}:80?path=/vless&encryption=none&type=ws#${user}"
vlesslink3="vless://${uuid}@${domain}:443?mode=gun&security=tls&encryption=none&type=grpc&serviceName=vless-service&sni=${domain}#${user}"
fi

clear
echo -e " ${TEAL}————————————————————————————————————${NC}"
echo -e "\033[37m         ❏ XRAY VLESS ❏\033[0m"
echo -e " ${TEAL}————————————————————————————————————${NC}"
echo -e "\033[37m Remarks     : ${user} "
echo -e "\033[37m Domain      : ${domain}"
echo -e "\033[37m User Quota  : ${Quota} GB"
echo -e "\033[37m User Ip     : ${iplimit} IP"
echo -e "\033[37m port TLS    : 443-900"
echo -e "\033[37m port WS     : 80,8880,8080"
echo -e "\033[37m User ID     : ${uuid}"
echo -e "\033[37m Locations.  : $CITY"
echo -e "\033[37m ISP         : $ISP"
echo -e "\033[37m Encryption  : none"
echo -e "\033[37m Path        : /vless "
echo -e "\033[37m ServiceName : vless-service"
echo -e " ${TEAL}————————————————————————————————————${NC}"
echo -e "\033[37m Link TLS    : ${vlesslink1}"
echo -e " ${TEAL}————————————————————————————————————${NC}"
echo -e "\033[37m Link NTLS   : ${vlesslink2}"
echo -e " ${TEAL}————————————————————————————————————${NC}"
echo -e "\033[37m Link GRPC   : ${vlesslink3}"
echo -e " ${TEAL}————————————————————————————————————${NC}"
echo -e "\033[33m  Expired On : $exp \033[0m "
echo -e " ${TEAL}————————————————————————————————————${NC}"
systemctl restart xray