#!/bin/bash

# Mendefinisikan warna untuk pesan
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[0;33m'
BIRU='\033[0;34m'
PURPLE='\033[0;35m'
CYAN='\033[0;36m'
CYAN_BG='\033[46;1;97m'   # Latar belakang cyan cerah dengan teks putih
LIGHT='\033[0;37m'
PINK='\033[0;35m'
ORANGE='\033[38;5;208m'
PINK_BG='\033[45;1;97m'
BIRU_BG='\033[44;1;97m'
RED_BG='\033[41;1;97m'   # Latar belakang pink cerah dengan teks putih
NC='\033[0m'
INDIGO='\033[38;5;54m'
TEAL='\033[38;5;30m'
WHITE='\033[1;37m'
clear

nama=$(cat /etc/xray/username)

function Loading_Succes() {
  clear

  # Karakter untuk animasi spinner
  spinner=( '|' '/' '-' '\' )

  # Simulasi animasi spinner
  for i in {1..3}; do
    for s in "${spinner[@]}"; do
      echo -ne "\r\033[1;33m[$s] Process Check Config Account... \033[0m"
      sleep 0.1
    done
  done

  # Tampilkan pesan sukses
  clear
  echo -e "\033[1;32m🎉 The process completed successfully! ✅\033[0m"
  sleep 1
  clear
}

  echo -e " ${TEAL}————————————————————————————————————${NC}"
  echo -e " ${PURPLE}      ❏ List Trojan Account ❏     ${NC}"
  echo -e " ${TEAL}————————————————————————————————————${NC}"     
  echo -e "              ${ORANGE}USERNAME${NC}"
  echo -e " ${TEAL}————————————————————————————————————${NC}"
  grep -E "^#! " "/etc/xray/config.json" | cut -d ' ' -f 2-3 | sort | uniq | while read -r user exp; do
  printf "  %-10s %s\n" "$user"  # Rata menggunakan printf
  done
  echo -e " ${TEAL}————————————————————————————————————${NC}"
  echo "" 
read -rp " ➣ Input Username: " user
    if [ -z $user ]; then
echo -e " ❌ User Tidak Ditemukan!!!"
read -n 1 -s -r -p "Enter Back To Menu"
sktaio-tro
else
CITY=$(cat /etc/xray/city)
ISP=$(cat /etc/xray/isp)
domain=$(cat /etc/xray/domain)
iplimit=$(cat /etc/saputratech/limit/trojan/ip/$user)
Quota1=$(cat /etc/trojan/$user)
Quota=$((Quota1 / 1024 / 1024 / 1024))
uuid=$(grep -E "^},{" "/etc/xray/config.json" |  grep -i '"'"${user}"'"' | cut -d " " -f 2 | cut -d '"' -f 2 | uniq )
exp=$(grep -E "^#! " "/etc/xray/config.json" | grep -i ' '"${user}"' ' | cut -d ' ' -f 3 | uniq )
trojanlink1="trojan://${uuid}@${domain}:443?mode=gun&security=tls&type=grpc&serviceName=trojan-service&sni=bug.com#${user}"
trojanlink="trojan://${uuid}@bugkamu.com:443?path=%2Ftrojan&security=tls&host=${domain}&type=ws&sni=${domain}#${user}"

fi

clear
echo -e " ${TEAL}————————————————————————————————————${NC}"
echo -e "${ungu}         ❏ XRAY TROJAN ACCOUNT ❏     ${NC}"
echo -e " ${TEAL}————————————————————————————————————${NC}"
echo -e " Username      : ${user}"
echo -e " User Quota    : ${Quota} GB"
echo -e " Limit IP      : ${iplimit} Device"
echo -e " Host/IP       : ${domain}"
echo -e " ISP           : ${ISP}"
echo -e " Country       : ${CITY}"
echo -e " Key           : ${uuid}"
echo -e " Port TLS      : 443"
echo -e " Port none TLS : 80"
echo -e " Network       : ws - grpc"
echo -e " Path          : /trojan"
echo -e " ServiceName   : trojan"
echo -e " ${TEAL}————————————————————————————————————${NC}"
echo -e " Link TLS      : ${trojanlink}"
echo -e " ${TEAL}————————————————————————————————————${NC}"
echo -e " Link GRPC     : ${trojanlink1}"
echo -e " ${TEAL}————————————————————————————————————${NC}"
echo -e "  Expired On    : $exp"
echo -e " ${TEAL}————————————————————————————————————${NC}"
echo -e ""
echo -e " ${TEAL}————————————————————————————————————${NC}"
echo -e " ${PURPLE}    Terimakasih Telah Menggunakan- ${NC}"
echo -e " ${PURPLE}  Script Credit By ROSI Store x SKT ${NC}"
echo -e " ${TEAL}————————————————————————————————————${NC}"
echo -e ""
systemctl restart xray