#!/bin/bash

RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[0;33m'
BIRU='\033[0;34m'
PURPLE='\033[0;35m'
CYAN='\033[0;36m'
CYAN_BG='\033[46;1;97m'   # Latar belakang cyan cerah dengan teks putih
LIGHT='\033[0;37m'
PINK='\033[0;35m'
ORANGE='\033[38;5;208m'
PINK_BG='\033[45;1;97m'
BIRU_BG='\033[44;1;97m'
RED_BG='\033[41;1;97m'   # Latar belakang pink cerah dengan teks putih
NC='\033[0m'
INDIGO='\033[38;5;54m'
TEAL='\033[38;5;30m'
WHITE='\033[1;37m'
clear

dateFromServer=$(curl -v --insecure --silent https://google.com/ 2>&1 | grep Date | sed -e 's/< Date: //')
biji=`date +"%Y-%m-%d" -d "$dateFromServer"`
nama=$(cat /etc/xray/username)

# Fungsi untuk menampilkan animasi spinner loading
function Loading_Succes() {
  clear

  # Karakter untuk animasi spinner
  spinner=( '|' '/' '-' '\' )

  # Simulasi animasi spinner
  for i in {1..3}; do
    for s in "${spinner[@]}"; do
      echo -ne "\r\033[1;33m[$s] The process of deleting an account... \033[0m"
      sleep 0.1
    done
  done

  # Tampilkan pesan sukses
  clear
  echo -e "\033[1;32m🎉 The process completed successfully! ✅\033[0m"
  sleep 1
  clear
}
NUMBER_OF_CLIENTS=$(grep -c -E "^#! " "/etc/xray/config.json")
	if [[ ${NUMBER_OF_CLIENTS} == '0' ]]; then
		clear
        echo -e " ${TEAL}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
        echo -e " ${PURPLE}      ❏ DELETE TROJAN ACCOUNT ❏ ${NC} "
        echo -e " ${TEAL}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
		    echo ""
		    echo -e "${RED} Nama Is Wrong !!! ${Xark} "
	    	echo ""
        echo -e " ${TEAL}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
        echo ""
        read -n 1 -s -r -p "Press any key to back on menu"
        menu
	fi
	    clear
        echo -e " ${TEAL}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
        echo -e " ${PURPLE}         ❏ DELETE TROJAN ACCOUNT ❏  ${Xark} "
        echo -e " ${TEAL}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
        echo -e " ${WHITE}  USER                         EXPIRED  ${NC}  " 
        echo -e " ${TEAL}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
	    echo ""
         grep -E "^#! " "/etc/xray/config.json" | cut -d ' ' -f 2-3 | sort | uniq | while read -r user exp; do
         printf "  %-28s %s\n" "$user" "$exp"  # Rata menggunakan printf
         done
        echo ""
        echo -e " ${TEAL}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
        echo ""
        read -rp " ➣ Input Username : " user
        echo ""
    if [ -z $user ]; then
    Loading_Succes
    menu
    else
    uuid=$(grep -E "###" "/etc/trojan/.trojan.db" |  grep -wE ${user} | awk '{print $4}' | uniq )
    exp=$(grep -wE "^#! $user" "/etc/xray/config.json" | cut -d ' ' -f 3 | sort | uniq)
    sed -i "/^#! $user $exp/,/^},{/d" /etc/xray/config.json
    echo "#! $user $uuid" >> /etc/xray/.userall.db
	sed -i "/^### $user $exp/,/^},{/d" /etc/vless/.vless.db
    rm -rf /etc/vless/$user
    rm -rf /etc/saputratech/limit/vless/ip
	rm -rf /var/www/html/vless-$user.txt
    systemctl restart xray > /dev/null 2>&1
    clear
    echo -e " ${TEAL}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
    echo -e " ${PURPLE}   DELETE TROJAAN ACCOUNT SUCCESSFULLY     ${NC}"
    echo -e " ${TEAL}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}" 
    echo -e ""
    echo -e " ${WHITE} ➥ Client Name ${NC}: ${YELLOW}$user ${NC} "
    echo -e " ${WHITE} ➥ Expired On  ${NC}: ${BLUE}$exp${NC} "
    echo -e ""
    echo -e " ${TEAL}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
    echo " "
    echo -e " ${TEAL}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
    echo -e " ${PURPLE}        Terimakasih Telah Menggunakan- ${NC}"
    echo -e " ${PURPLE} Script Credit By ROSI Store Project ${NC}"
    echo -e " ${TEAL}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
    echo ""
    systemctl restart xray
    read -n 1 -s -r -p "    Press any key to back on menu"
    menu
    fi
