#!/bin/bash
# ==========================================
# Color
# Warna untuk tampilan menu
# Mendefinisikan warna untuk pesan
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[0;33m'
BIRU='\033[0;34m'
PURPLE='\033[0;35m'
CYAN='\033[0;36m'
CYAN_BG='\033[46;1;97m'   # Latar belakang cyan cerah dengan teks putih
LIGHT='\033[0;37m'
PINK='\033[0;35m'
ORANGE='\033[38;5;208m'
PINK_BG='\033[45;1;97m'
BIRU_BG='\033[44;1;97m'
RED_BG='\033[41;1;97m'   # Latar belakang pink cerah dengan teks putih
NC='\033[0m'
INDIGO='\033[38;5;54m'
TEAL='\033[38;5;30m'
WHITE='\033[1;37m'
# ==========================================
clear

echo -e " ${TEAL}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo -e "           📜 ${PURPLE}REMOVE MEMBER SSH${NC} 📜                  "
echo -e " ${TEAL}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo -e "   ${YELLOW}NO${NC}   ${YELLOW}USERNAME${NC}            ${RED}EXP DATE${NC}          "
echo -e " ${TEAL}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"

# Menampilkan daftar user dengan nomor
users=()
i=1
while read expired; do
  AKUN="$(echo $expired | cut -d: -f1)"
  ID="$(echo $expired | grep -v nobody | cut -d: -f3)"
  exp="$(chage -l $AKUN | grep "Account expires" | awk -F": " '{print $2}')"
  if [[ $ID -ge 1000 ]]; then
    users+=("$AKUN") # Tambahkan user ke array
    printf "  %2d. %-20s %-20s \n" "$i" "$AKUN" "$exp"
    ((i++))
  fi
done < /etc/passwd

echo -e " ${TEAL}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo -e "             SELECT USING NUMBER                   "
echo -e " ${TEAL}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo ""

# Meminta input dari pengguna
read -p " ➣ Your Choice: " choice

# Validasi input
if [[ "$choice" =~ ^[0-9]+$ ]] && [[ "$choice" -ge 1 ]] && [[ "$choice" -le ${#users[@]} ]]; then
  user="${users[$((choice-1))]}"
  if getent passwd "$user" > /dev/null 2>&1; then
    userdel "$user" > /dev/null 2>&1
    sed -i "/^$user:/d" /etc/group
    exp=$(grep -w "^#ssh# $user" "/etc/ssh/.ssh.db" | cut -d ' ' -f 3 | sort | uniq)
    grep -wE "^#ssh# $user" "/etc/ssh/.ssh.db" | awk '{print $1" "$2" "$3}' | sort | uniq | tail -1 >> /etc/xray/.userall.db
    sed -i "/^#ssh# $user/d" /etc/ssh/.ssh.db
    rm -f /etc/ssh/$user
    rm -f /etc/saputratech/limit/ssh/ip/${user}
    rm -f /var/www/html/ssh-$user.txt
    echo -e ""
    echo -e " ${GREEN}Success:${NC} User '${YELLOW}$user${NC}' has been successfully deleted."
  else
    echo -e "${RED}Failure:${NC} User '$user' not found."
  fi
else
  echo -e "${RED}Invalid choice.${NC} Please select a valid number."
fi
