#!/bin/bash

RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[0;33m'
BIRU='\033[0;34m'
PURPLE='\033[0;35m'
CYAN='\033[0;36m'
CYAN_BG='\033[46;1;97m'   # Latar belakang cyan cerah dengan teks putih
LIGHT='\033[0;37m'
PINK='\033[0;35m'
ORANGE='\033[38;5;208m'
PINK_BG='\033[45;1;97m'
BIRU_BG='\033[44;1;97m'
RED_BG='\033[41;1;97m'   # Latar belakang pink cerah dengan teks putih
NC='\033[0m'
INDIGO='\033[38;5;54m'
TEAL='\033[38;5;30m'
WHITE='\033[1;37m'
clear

# Menampilkan pesan setelah animasi selesai
function Loading_Succes() {
  clear

  # Karakter untuk animasi spinner
  spinner=( '|' '/' '-' '\' )

  # Simulasi animasi spinner
  for i in {1..3}; do
    for s in "${spinner[@]}"; do
      echo -ne "\r\033[1;33m[$s] Changed IP Limit Process... \033[0m"
      sleep 0.1
    done
  done

  # Tampilkan pesan sukses
  clear
  echo -e "\033[1;32m🎉 The process completed successfully! ✅\033[0m"
  sleep 1
  clear
}
echo -e " ${CYAN}==========================================${NC}"
echo -e " ${PURPLE}      CHANGE IP LIMIT SSH ACCOUNT         ${NC} "
echo -e " ${CYAN}==========================================${NC}"
echo -e "${TEAL}┌──────────────────────────────────────────┐${NC}"
echo "   USERNAME       EXP DATE         STATUS"
echo -e "${TEAL}└──────────────────────────────────────────┘${NC}"
echo -e "${TEAL}┌──────────────────────────────────────────┐${NC}"
while read expired
do
AKUN="$(echo $expired | cut -d: -f1)"
ID="$(echo $expired | grep -v nobody | cut -d: -f3)"
exp="$(chage -l $AKUN | grep "Account expires" | awk -F": " '{print $2}')"
status="$(passwd -S $AKUN | awk '{print $2}' )"
if [[ $ID -ge 1000 ]]; then
if [[ "$status" = "L" ]]; then
 printf "%-17s %2s %-17s %2s \n" "  $AKUN" "$exp   " "LOCKED${NORMAL}"
else
 printf "%-17s %2s %-17s %2s \n" "  $AKUN" "$exp   " "UNLOCKED${NORMAL}"
fi
fi
done < /etc/passwd
JUMLAH="$(awk -F: '$3 >= 1000 && $1 != "nobody" {print $1}' /etc/passwd | wc -l)"
echo -e "${TEAL}└──────────────────────────────────────────┘${NC}"
echo -e "${TEAL}┌──────────────────────────────────────────┐${NC}"
echo "  ➣ Account number: $JUMLAH user"
echo -e "${TEAL}└──────────────────────────────────────────┘${NC}"
echo -e ""
read -p " ➣ input username: " user
limit_file="/etc/saputratech/limit/ssh/ip/$user"

# Validasi apakah file batasan IP sudah ada
if [ -e "$limit_file" ]; then
  current_iplimit=$(cat "$limit_file")
  clear
  echo -e ""
  echo -e "${CYAN} ❑ Change New IP Limit SSH Account ❑ ${NC} "
  echo -e ""
  read -p " ➣ Input New Limit   : " new_iplimit

Loading_Animasi
Loading_Succes


  # Validasi jika masukan kosong
  if [ -z "$new_iplimit" ]; then
    echo -e "${White} Invallid !! "
  else
    echo "$new_iplimit" > "$limit_file"
    echo -e " ${TEAL}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
    echo -e "   CHANGE IP LIMIT SSH ACCOUNT SUCCESSFULLY           "
    echo -e " ${TEAL}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}" 
    echo -e ""
    echo -e " ${WHITE} ➥ Username ${NC}    : ${YELLOW}$user ${NC} "
    echo -e " ${WHITE} ➥ New Limit IP ${NC}: ${GREEN}$new_iplimit Device${NC} "
    echo -e ""
    echo -e " ${TEAL}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
    echo " "
    echo -e " ${TEAL}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
    echo -e " ${PURPLE}        Terimakasih Telah Menggunakan- ${NC}"
    echo -e " ${PURPLE} Script Credit By ROSI Store x SKT Project ${NC}"
    echo -e " ${TEAL}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
  fi
else

  echo -e "${RED} Error, Sorry!... ${NC} "
echo ""
  echo -e "${WHITE} ➥ Username   : $user "
  echo -e "${WHITE} ➥ IP LIMIT   : ${NC} ${RED}invallid !! ${NC} "
echo ""
baris_panjang
Sc_Credit

fi
