#!/bin/bash

# Mendefinisikan warna untuk pesan
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[0;33m'
BIRU='\033[0;34m'
PURPLE='\033[0;35m'
CYAN='\033[0;36m'
CYAN_BG='\033[46;1;97m'   # Latar belakang cyan cerah dengan teks putih
LIGHT='\033[0;37m'
PINK='\033[0;35m'
ORANGE='\033[38;5;208m'
PINK_BG='\033[45;1;97m'
BIRU_BG='\033[44;1;97m'
RED_BG='\033[41;1;97m'   # Latar belakang pink cerah dengan teks putih
NC='\033[0m'
INDIGO='\033[38;5;54m'
TEAL='\033[38;5;30m'
WHITE='\033[1;37m'

clear
red() { echo -e "\\033[32;1m${*}\\033[0m"; }
clear
#IZIN SCRIPT
MYIP=$(curl -sS ipv4.icanhazip.com)
echo -e "\e[32mloading...\e[0m"
clear
red() { echo -e "\\033[32;1m${*}\\033[0m"; }

# // Get Bot
CHATID=$(grep -E "^#bot# " "/etc/bot/.bot.db" | cut -d ' ' -f 3)
KEY=$(grep -E "^#bot# " "/etc/bot/.bot.db" | cut -d ' ' -f 2)
export TIME="10"
export URL="https://api.telegram.org/bot$KEY/sendMessage"
clear

# Valid Script
ipsaya=$(curl -sS ipv4.icanhazip.com)
data_server=$(curl -v --insecure --silent https://google.com/ 2>&1 | grep Date | sed -e 's/< Date: //')
date_list=$(date +"%Y-%m-%d" -d "$data_server")
data_ip="https://raw.githubusercontent.com/rosi606/1z1n/main/L1cense.txt"
checking_sc() {
  useexp=$(wget -qO- $data_ip | grep $ipsaya | awk '{print $3}')
  if [[ $date_list < $useexp ]]; then
    echo -ne
  else
    echo -e " ${CYAN}=======================================${NC}"
    echo -e " ${RED} TERTOLAK MENTAH MENTAH MAMPUS AWOKWOK ${NC}"
    echo -e " ${CYAN}=======================================${NC}"
    echo -e ""
    echo -e " ⛔${RED} PERMISSION DENIED... !${NC}"
    echo -e " Your IP: ${RED}$ipsaya${NC} Has been Banned"
    echo -e ""
    echo -e " 📞 Contact Admin :"
    echo -e " 🌍 Telegram: https://wa.me/6281931472448"
    echo -e ""
    echo -e " ${CYAN}=======================================${NC}"
    sleep 1
    exit
  fi
}
checking_sc
clear
export TIME="10"
IP=$(curl -sS ipv4.icanhazip.com)
ISP=$(cat /etc/xray/isp)
CITY=$(cat /etc/xray/city)
domain=$(cat /etc/xray/domain)
nama=$(cat /etc/xray/username)
clear

LIMITSSH_SCRIPT="/usr/local/sbin/limitssh-ip"
CRON_FILE="/etc/cron.d/limitssh-ip"

check_cron_status() {
    if [ -e "$CRON_FILE" ]; then
        echo -e " ${PURPLE} ❐ Status Limit IP :${NC} ${GREEN}[ON]${NC}"
    else
        echo -e " ${PURPLE} ❐ Status Limit IP :${NC} ${RED}[OFF]${NC}"
    fi
}

start_cron() {
clear
    # Input menit dari pengguna
echo -e " ${CYAN}======================================${NC}"
echo -e " ${PURPLE}       AUTOKILL SSH MULTI LOGIN         ${NC} "
echo -e " ${CYAN}======================================${NC}"
echo -e " ${WHITE}Just input a number in${NC} - ${YELLOW}Limit ip ssh${NC}"
echo ""
echo -e " ${WHITE}❑ Example, Format minutes: ${NC}"
echo -e " ${GREEN} Input 5${NC}  for  ${WHITE}5 minutes ${NC}"
echo -e " ${GREEN} Input 60${NC}  for  ${WHITE}60 minutes ${NC}"
echo ""
echo -e " ${CYAN}======================================${NC}"
echo ""
    read -p " ➣ Input minutes: " menit
sleep 3 & loading $!

    # Validasi input
    if [[ ! "$menit" =~ ^[1-9]$|^[1-5][0-9]$ ]]; then
        echo -e "${RED}Input tidak valid.${NC}"
        return
    fi

    # Membuat isi tugas cron
    CRON_ENTRY="*/$menit * * * * root $LIMITSSH_SCRIPT"

    # Menambahkan atau memperbarui tugas cron
    echo -e "SHELL=/bin/sh\nPATH=/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin\n$CRON_ENTRY" | tee "$CRON_FILE" > /dev/null

    # Pastikan izin file dan tugas cron
    chmod +x "$LIMITSSH_SCRIPT"
    chmod 644 "$CRON_FILE"

    # Menampilkan isi dari /etc/cron.d/limitssh-ip
    echo -e "Isi dari $CRON_FILE:"
    cat "$CRON_FILE"
    
clear
echo -e " ${TEAL}======================================${NC}"
check_cron_status
echo -e " ${YELLOW} ❏ Auto Shutdown   :${NC} $menit minutes"
echo ""
echo -e " ${TEAL}======================================${NC}"
read -p " ➣ Enter Back To Menu"
Lt-on-off
}

stop_cron() {
    rm -f "$CRON_FILE"
    echo -e " ${TEAL}======================================${NC}"
    echo ""
    echo -e " ❏ Status  : ${RED}Non Active${NC}"
    echo ""
    echo -e " ${TEAL}======================================${NC}"
}



function Environment(){
clear
echo -e " ${TEAL}======================================${NC}"
check_cron_status
echo -e " ${TEAL}======================================${NC}"
echo ""
echo -e " ${YELLOW} 1.${NC}  ${WHITE}Start Limit Ip ssh ${NC}"
echo -e " ${YELLOW} 2.${NC}  ${WHITE}Stopp Limit Ip ssh ${NC}"
echo -e " ${YELLOW} 3.${NC}  ${WHITE}Check Status Limit ${NC}"
echo -e " ${YELLOW} x.${NC}  ${RED}EXIT ${NC}"
echo ""
echo -e " ${TEAL}======================================${NC}"
echo ""
}
Environment
read -p " ➣ Your Choice:  " REPLY
    case $REPLY in
        1)
            start_cron
            ;;
        2)
            stop_cron
            ;;
        3)
            check_cron_status
            ;;
        *)
            exit
            ;;
    esac