#!/bin/bash
# Mendefinisikan warna untuk pesan
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[0;33m'
BIRU='\033[0;34m'
PURPLE='\033[0;35m'
CYAN='\033[0;36m'
CYAN_BG='\033[46;1;97m'   # Latar belakang cyan cerah dengan teks putih
LIGHT='\033[0;37m'
PINK='\033[0;35m'
ORANGE='\033[38;5;208m'
PINK_BG='\033[45;1;97m'
BIRU_BG='\033[44;1;97m'
RED_BG='\033[41;1;97m'   # Latar belakang pink cerah dengan teks putih
NC='\033[0m'
INDIGO='\033[38;5;54m'
TEAL='\033[38;5;30m'
WHITE='\033[1;37m'
clear

#Banner Ssh
  echo -e " ${CYAN}======================================${NC}"
  echo -e " ${RED_BG}               FEATURES              ${NC}"
  echo -e " ${CYAN}======================================${NC}"
  echo -e ""
  echo -e "  1.) Install ADS Block "  
  echo -e "  2.) Running Service   " 
  echo -e "  3.) Restart Service 	 "
  echo -e " ${CYAN}======================================${NC}"
  echo -e " ${BIRU_BG}               MENU FIX              ${NC}"
  echo -e " ${CYAN}======================================${NC}"
  echo -e "  4.) Change Banner      "  
  echo -e "  5.) Change Domain      "  
  echo -e "  6.) Fix Haproxy Off    "  
  echo -e "  7.) Renew Cert Xray    " 
  echo -e " ${CYAN}======================================${NC}"
  echo -e " ${BIRU_BG}           MENU INFORMATION          ${NC}"
  echo -e " ${CYAN}======================================${NC}"
  echo -e "  8.) Info Service Port  "
  echo -e "  9.) Set Limit IP & Quota XRAY  "
  echo -e " ${CYAN}======================================${NC}"
  echo -e " ${BIRU_BG}             ADMIN ACCESS            ${NC}"
  echo -e " ${CYAN}======================================${NC}"
  echo -e "  10.) Setup BOT Telegram Notif"
  echo -e " ${CYAN}======================================${NC}"
  echo -e " ${BIRU_BG}       MENU BACKUP x RESTORE       ${NC}"
  echo -e " ${CYAN}======================================${NC}"
  echo -e "  11. Auto Backup VPS Data "
  echo -e "  12. Restore VPS Data Via SFTP "
  echo -e " ${CYAN}======================================${NC}"
  echo -e "  x.) Back to Menu       "
  echo -e " "
  echo -e " ${CYAN}======================================${NC}"
  echo -e " "

read -p "  ➣ Your Choice: " NB
case $NB in
      1) echo -e "${TEAL} ➣ Service ADS Block selected ${NC}"
         rm -rf /usr/local/sbin/helium && wget -q -O /usr/local/sbin/helium https://raw.githubusercontent.com/abidarwish/helium/main/helium.sh && chmod +x /usr/local/sbin/helium && helium
         ;;
      2) echo -e "${TEAL} ➣ Service Check Service selected ${NC}" 
         phreakers-cek 
         ;;
      3) echo -e "${TEAL} ➣ Service Restart Service selected ${NC}" 
         phreakers-reset
         ;;
      4) echo -e "${TEAL} ➣ Service Change Banner selected ${NC}" 
         nano /etc/skt-banner.txt
         ;;
      5) echo -e "${TEAL} ➣ Service Change Domain selected ${NC}" 
         change-domain
         ;;
      6) echo -e "${TEAL} ➣ Service FIX Haproxy selected ${NC}" 
         phreakers-fixhap
         ;;
      7) echo -e "${TEAL} ➣ Service Fix Certificat selected ${NC}" 
         phreakers-fixcert 
         ;;
      8) echo -e "${TEAL} ➣ Service Check Port selected ${NC}" 
         phreakers-info-port
         ;;
      9) echo -e "${TEAL} ➣ Service Change LImit IP Xray selected ${NC}" 
         limit-on-off 
         ;;
      10) echo -e "${TEAL} ➣ Service BOT Notification selected ${NC}" 
         skt-bot-create-telegram-notif
         ;;
      11) echo -e "${TEAL} ➣ Service AutoBackup VPS Data selected ${NC}" 
         tr -d '\r' < /usr/local/sbin/skarti-bysftp-backup > /tmp/fixed-script && mv /tmp/fixed-script /usr/local/sbin/skarti-bysftp-backup && chmod +x /usr/local/sbin/skarti-bysftp-backup && tr -d '\r' < /usr/local/sbin/phreakers-fitur > /tmp/fixed-script && mv /tmp/fixed-script /usr/local/sbin/phreakers-fitur && chmod +x /usr/local/sbin/phreakers-fitur && skarti-bysftp-backup 
         ;;
      12) echo -e "${TEAL} ➣ Service Restore VPS Data selected ${NC}"
         tr -d '\r' < /usr/local/sbin/skarti-bysftp-restore > /tmp/fixed-script && mv /tmp/fixed-script /usr/local/sbin/skarti-bysftp-restore && chmod +x /usr/local/sbin/skarti-bysftp-restore && tr -d '\r' < /usr/local/sbin/phreakers-fitur > /tmp/fixed-script && mv /tmp/fixed-script /usr/local/sbin/phreakers-fitur && chmod +x /usr/local/sbin/phreakers-fitur && skarti-bysftp-restore
         ;;
      x) clear ; menu ;;
      *) phreakers-fitur ;;
esac