#!/bin/bash

# Mendefinisikan warna untuk pesan
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[0;33m'
BIRU='\033[0;34m'
PURPLE='\033[0;35m'
CYAN='\033[0;36m'
CYAN_BG='\033[46;1;97m'   # Latar belakang cyan cerah dengan teks putih
LIGHT='\033[0;37m'
PINK='\033[0;35m'
ORANGE='\033[38;5;208m'
PINK_BG='\033[45;1;97m'
BIRU_BG='\033[44;1;97m'
RED_BG='\033[41;1;97m'   # Latar belakang pink cerah dengan teks putih
NC='\033[0m'
INDIGO='\033[38;5;54m'
TEAL='\033[38;5;30m'
WHITE='\033[1;37m'
clear

CHATID=$(grep -E "^#bot# " "/etc/bot/.bot.db" | cut -d ' ' -f 3)
KEY=$(grep -E "^#bot# " "/etc/bot/.bot.db" | cut -d ' ' -f 2)
export TIME="10"
export URL="https://api.telegram.org/bot$KEY/sendMessage"
clear

# Valid Script
ipsaya=$(curl -sS ipv4.icanhazip.com)
data_server=$(curl -v --insecure --silent https://google.com/ 2>&1 | grep Date | sed -e 's/< Date: //')
date_list=$(date +"%Y-%m-%d" -d "$data_server")
data_ip="https://raw.githubusercontent.com/Panwas89/1z1n/L1cense"
checking_sc() {
  useexp=$(wget -qO- $data_ip | grep $ipsaya | awk '{print $3}')
  if [[ $date_list < $useexp ]]; then
    echo -ne
  else
    echo -e " ${CYAN}=======================================${NC}"
    echo -e " ${RED} TERTOLAK MENTAH MENTAH MAMPUS AWOKWOK ${NC}"
    echo -e " ${CYAN}=======================================${NC}"
    echo -e ""
    echo -e " ⛔${RED} PERMISSION DENIED... !${NC}"
    echo -e " Your IP: ${RED}$ipsaya${NC} Has been Banned"
    echo -e ""
    echo -e " 📞 Contact Admin :"
    echo -e " 🌍 Telegram: https://wa.me/6281931472448"
    echo -e ""
    echo -e " ${CYAN}=======================================${NC}"
    sleep 1
    sleep 10
	reboot
  fi
}
checking_sc
clear
export TIME="10"
IP=$(curl -sS ipv4.icanhazip.com)
ISP=$(cat /etc/xray/isp)
CITY=$(cat /etc/xray/city)
domain=$(cat /etc/xray/domain)
nama=$(cat /etc/xray/username)
clear

# Fungsi untuk menampilkan animasi spinner loading
function Loading_Succes() {
  clear

  # Karakter untuk animasi spinner
  spinner=( '|' '/' '-' '\' )

  # Simulasi animasi spinner
  for i in {1..3}; do
    for s in "${spinner[@]}"; do
      echo -ne "\r\033[1;33m[$s] Process Recovery Account... \033[0m"
      sleep 0.1
    done
  done

  # Tampilkan pesan sukses
  clear
  echo -e "\033[1;32m🎉 The process completed successfully! ✅\033[0m"
  sleep 1
  clear
}

function Daftar_Account() {
grep -E "^#! " "/etc/xray/.userall.db" | cut -d ' ' -f 2-3 | column -t | sort | uniq
}

MYIP=$(curl -sS ipv4.icanhazip.com);
clear
  echo -e " ${TEAL}————————————————————————————————————${NC}"
  echo -e " ${PURPLE}      ❏ List Trojan Expired ❏     ${NC}"
  echo -e " ${TEAL}————————————————————————————————————${NC}"     
  echo -e "              ${ORANGE}USERNAME${NC}"
  echo -e " ${TEAL}————————————————————————————————————${NC}"
  grep -E "^#! " "/etc/xray/.userall.db" | cut -d ' ' -f 2-3 | sort | uniq | while read -r user exp; do
  printf "  %-28s %s\n" "$user"  # Rata menggunakan printf
  done
  echo -e " ${TEAL}————————————————————————————————————${NC}"
  echo "" 
	read -p " ➣ Your Choice: " user
	if [ -z $user ]; then
    exit
    else
  echo -e " ${TEAL}————————————————————————————————————${NC}"
    read -p " Expired (Days)    : " masaaktif
      echo -e " ${TEAL}————————————————————————————————————${NC}"
    read -p " Limit User (GB)  : " Quota
      echo -e " ${TEAL}————————————————————————————————————${NC}"
    read -p " Limit User (IP)  : " iplimit
  echo -e " ${TEAL}————————————————————————————————————${NC}"
echo ""
fi
Loading_Succes
systemctl restart xray
clear
uuid=$(grep -E "^#!" "/etc/xray/.userall.db" |  grep -wE "${user}" | cut -d " " -f 3)
if [ -z $uuid ]; then
  echo -e " ${TEAL}————————————————————————————————————${NC}"
echo -e "        Recovery Account Failed!             "
  echo -e " ${TEAL}————————————————————————————————————${NC}"
echo -e ""
echo -e "   Username Tidak Ditemukan      "
echo -e ""
  echo -e " ${TEAL}————————————————————————————————————${NC}"
echo -e ""
read -n 1 -s -r -p "Press any key to back"
exit 1
else
tgl=$(date -d "$masaaktif days" +"%d")
bln=$(date -d "$masaaktif days" +"%b")
thn=$(date -d "$masaaktif days" +"%Y")
expe="$tgl $bln, $thn"
tgl2=$(date +"%d")
bln2=$(date +"%b")
thn2=$(date +"%Y")
tnggl="$tgl2 $bln2, $thn2"
exp=`date -d "$masaaktif days" +"%Y-%m-%d"`
sed -i '/#trojanws$/a\#! '"$user $exp"'\
},{"password": "'""$uuid""'","email": "'""$user""'"' /etc/xray/config.json
sed -i '/#trojangrpc$/a\#! '"$user $exp"'\
},{"password": "'""$uuid""'","email": "'""$user""'"' /etc/xray/config.json

# Link Trojan Akun
systemctl restart xray
trojanlink1="trojan://${uuid}@${domain}:443?mode=gun&security=tls&type=grpc&serviceName=trojan-service&sni=bug.com#${user}"
trojanlink="trojan://${uuid}@bugkamu.com:443?path=%2Ftrojan&security=tls&host=${domain}&type=ws&sni=${domain}#${user}"

trojanlink="trojan://${uuid}@${domain}:443?path=%2Ftrojan&security=tls&host=${domain}&type=ws&sni=${domain}#${user}"
trojanlink1="trojan://${uuid}@${domain}:443?mode=gun&security=tls&type=grpc&serviceName=trojan-service&sni=${domain}#${user}"
if [ ! -e /etc/trojan ]; then
  mkdir -p /etc/trojan
fi

if [[ $iplimit -gt 0 ]]; then
mkdir -p /etc/saputratech/limit/trojan/ip
echo -e "$iplimit" > /etc/saputratech/limit/trojan/ip/$user
else
echo > /dev/null
fi

if [ -z ${Quota} ]; then
  Quota="0"
fi

c=$(echo "${Quota}" | sed 's/[^0-9]*//g')
d=$((${c} * 1024 * 1024 * 1024))

if [[ ${c} != "0" ]]; then
  echo "${d}" >/etc/trojan/${user}
fi
DATADB=$(cat /etc/trojan/.trojan.db | grep "^###" | grep -w "${user}" | awk '{print $2}')
if [[ "${DATADB}" != '' ]]; then
  sed -i "/\b${user}\b/d" /etc/trojan/.trojan.db
  echo "### ${user} ${exp} ${uuid} ${Quota} ${iplimit}" >>/etc/trojan/.trojan.db
else
echo "### ${user} ${exp} ${uuid} ${Quota} ${iplimit}" >>/etc/trojan/.trojan.db
fi
curl -s --max-time $TIMES -d "chat_id=$CHATID&disable_web_page_preview=1&text=$TEXT&parse_mode=html" $URL
clear
CHATID="$CHATID"
KEY="$KEY"
TIME="$TIME"
URL="$URL"
TEXT="<code>◇━━━━━━━━━━━━━━━━━◇</code>
<code>      XRAY/TROJAN</code>
<code>◇━━━━━━━━━━━━━━━━━◇</code>
<code>Remarks   : ${user}
Domain    : ${domain}
Limit Quota : ${Quota} GB
Port TLS  : 400-900
Port NTLS : 80, 8080, 8081-9999
id        : ${uuid}
alterId   : 0
Security  : auto
network   : ws or grpc
Path      : /Multi-Path
Dynamic   : https://bugmu.com/path
Name      : trojan-service</code>
<code>◇━━━━━━━━━━━━━━━━━◇</code>
Format OpenClash : https://${domain}:81/trojan-$user.txt
<code>◇━━━━━━━━━━━━━━━━━◇</code>
Aktif Selama   : $masaaktif Hari
Dibuat Pada    : $tnggl
Berakhir Pada  : $expe
<code>◇━━━━━━━━━━━━━━━━━◇</code>
"
curl -s --max-time $TIME -d "chat_id=$CHATID&disable_web_page_preview=1&text=$TEXT&parse_mode=html" $URL >/dev/null

fi
clear
echo -e " ${TEAL}————————————————————————————————————${NC}"
echo -e "${ungu}         ❏ XRAY TROJAN ACCOUNT ❏     ${NC}"
echo -e " ${TEAL}————————————————————————————————————${NC}"
echo -e " Username      : ${user}"
echo -e " User Quota    : ${Quota} GB"
echo -e " Limit IP      : ${iplimit} Device"
echo -e " Host/IP       : ${domain}"
echo -e " ISP           : ${ISP}"
echo -e " Country       : ${CITY}"
echo -e " Key           : ${uuid}"
echo -e " Port TLS      : 443"
echo -e " Port none TLS : 80"
echo -e " Network       : ws - grpc"
echo -e " Path          : /trojan"
echo -e " ServiceName   : trojan"
echo -e " ${TEAL}————————————————————————————————————${NC}"
echo -e " Link TLS      : ${trojanlink}"
echo -e " ${TEAL}————————————————————————————————————${NC}"
echo -e " Link GRPC     : ${trojanlink1}"
echo -e " ${TEAL}————————————————————————————————————${NC}"
echo -e "  Expired On    : $expe"
echo -e " ${TEAL}————————————————————————————————————${NC}"
echo -e ""
echo -e " ${TEAL}————————————————————————————————————${NC}"
echo -e " ${PURPLE}    Terimakasih Telah Menggunakan- ${NC}"
echo -e " ${PURPLE}  Script Credit By ROSI Store ${NC}"
echo -e " ${TEAL}————————————————————————————————————${NC}"
echo -e ""
systemctl restart xray
