#!/bin/bash

RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[0;33m'
BIRU='\033[0;34m'
PURPLE='\033[0;35m'
CYAN='\033[0;36m'
CYAN_BG='\033[46;1;97m'   # Latar belakang cyan cerah dengan teks putih
LIGHT='\033[0;37m'
PINK='\033[0;35m'
ORANGE='\033[38;5;208m'
PINK_BG='\033[45;1;97m'
BIRU_BG='\033[44;1;97m'
RED_BG='\033[41;1;97m'   # Latar belakang pink cerah dengan teks putih
NC='\033[0m'
INDIGO='\033[38;5;54m'
TEAL='\033[38;5;30m'
WHITE='\033[1;37m'

# Fungsi untuk restore data bysftp
clear
cd
unzip backup-bysftp.zip
sleep 1
cd /root/backup-bysftp
cp passwd /etc/
cp group /etc/
cp shadow /etc/
cp gshadow /etc/ 
cp .bot.db /etc/bot/
cp -r saputratech /var/lib/
cp -r xray /etc/
cp -r html /var/www/
cp crontab /etc/
cp .ssh.db /etc/ssh/
cp .vmess.db /etc/vmess/
cp .vless.db /etc/vless/
cp .trojan.db /etc/trojan/
cp -rf qt/* /etc/limit
cp -r limit /etc/saputratech/
cp -r vmess /etc/
cp -r trojan /etc/
cp -r vless /etc/
rm -rf /root/backup-bysftp
rm -rf /root/backup-bysftp.zip
clear
# Jalankan proses restore
echo -e "${TEAL}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo -e "${GREEN} ❐ Done, restore your Database, By SFTP ❐${NC}"
echo -e "${TEAL}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"