#!/bin/bash
clear

date=$(date +"%Y-%m-%d")
vps_ip=$(curl -s ifconfig.me) # Mendapatkan IP VPS
domain=$(cat /etc/xray/domain 2>/dev/null || echo "Tidak ditemukan") # Mendapatkan domain, jika ada

RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[0;33m'
BIRU='\033[0;34m'
PURPLE='\033[0;35m'
CYAN='\033[0;36m'
CYAN_BG='\033[46;1;97m'   # Latar belakang cyan cerah dengan teks putih
LIGHT='\033[0;37m'
PINK='\033[0;35m'
ORANGE='\033[38;5;208m'
PINK_BG='\033[45;1;97m'
BIRU_BG='\033[44;1;97m'
RED_BG='\033[41;1;97m'   # Latar belakang pink cerah dengan teks putih
NC='\033[0m'
INDIGO='\033[38;5;54m'
TEAL='\033[38;5;30m'
WHITE='\033[1;37m'


# Fungsi untuk backup data manual
clear
source /etc/skt/token.json
if [ -f "/etc/skt/token.json" ]; then
rm -rf /root/backup-bysftp
mkdir /root/backup-bysftp
cp /etc/passwd backup-bysftp/
cp /etc/group backup-bysftp/
cp /etc/shadow backup-bysftp/
cp /etc/gshadow backup-bysftp/
cp /etc/crontab backup-bysftp/
cp /etc/vmess/.vmess.db backup-bysftp/
cp /etc/ssh/.ssh.db backup-bysftp/
cp /etc/vless/.vless.db backup-bysftp/
cp /etc/trojan/.trojan.db backup-bysftp/
cp /etc/bot/.bot.db backup-bysftp/
cp -r /etc/saputratech/limit backup-bysftp/
cp -r /etc/limit backup-bysftp/qt/
cp -r /etc/vmess backup-bysftp/
cp -r /etc/trojan backup-bysftp/
cp -r /etc/vless backup-bysftp/
cp -r /var/lib/saputratech/ backup-bysftp/saputratech 
cp -r /etc/xray backup-bysftp/xray
cp -r /var/www/html/ backup-bysftp/html
cd /root
zip -r backup-bysftp.zip backup-bysftp > /dev/null 2>&1
curl -F chat_id="${ID}" \
     -F document=@"/root/backup-bysftp.zip" -F caption="
=================================
『 Successfully backup your Database 』
=================================
◈ IP VPS  : ${vps_ip}
◈ DOMAIN  : ${domain}
◈ Tanggal : ${date}
◈ Version : 1.0 Stable 
◈ Built By  : @SaputraTech 
================================= 
➣ How To Restore ?
➣ Use SFTP
➣ Go to /root
➣ Replace file backup-bysftp.zip
================================= 
         🍀 GENERATE BY SFTP 🍀 
================================= 
" https://api.telegram.org/bot${TOKEN}/sendDocument &> /dev/null

cd /root
echo -e " ${TEAL}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo -e " ${PINK}      ❐ MENU MANUAL BACKUP ❐ ${NC}"
echo -e " ${TEAL}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo -e " ${ORANGE}     🍀 POWERED BY CHATGPT 🍀  ${NC}"
echo -e " ${TEAL}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo -e " ${TEAL}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}" 
echo -e " ${GREEN}      ❐ Successfully Backup ❐${NC}"
echo -e " ${TEAL}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo -e " ${TEAL}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo -e " ${GREEN} File backup terkirim ke Telegram BOT.${NC}"
echo -e " ${TEAL}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo -e " ${TEAL}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo -e " ${PURPLE}   Terimakasih Telah Menggunakan-${NC}"
echo -e " ${PURPLE}     Script Credit By ROSI Store x SKT Project ${NC}"
echo -e " ${TEAL}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
exit 0
fi
echo -e "${TEAL}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo -e "${RED}     ❐ BOT TOKEN TIDAK TERSEDIA ❐${NC}"
echo -e "${TEAL}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
sleep 1
clear
mkdir -p /etc/skt/
    echo -e "${CYAN}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
    echo -e "${PURPLE}       ❐ MENU MANUAL BACKUP ❐ ${NC}"
    echo -e "${CYAN}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
    echo -e "${CYAN}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
    read -p "$(echo -e "${ORANGE}➽ Masukkan API Key bot Telegram Kamu: ${NC}")" token
    echo -e "${CYAN}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
sleep 0.2
    read -p "$(echo -e "${PINK}➽ Masukkan Chat ID Telegram Kamu: ${NC}")" id
sleep 1
echo "
TOKEN="${token}"
ID="${id}"
" >/etc/skt/token.json

# Fungsi untuk mengaktifkan crontab
enable_crontab() {
    echo -e "${CYAN}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
    echo -e ""
    clear
    read -p "$(echo -e " ❖${YELLOW} Aktifkan crontab setiap 30 menit? (y/N): ${NC}")" enable_crontab
    if [[ "$enable_crontab" =~ ^[Yy]$ ]]; then
        (crontab -l 2>/dev/null; echo "*/30 * * * * /usr/local/sbin/skarti-bysftp-backup") | crontab -
        echo -e " ❖${GREEN} Crontab telah diaktifkan.${NC}"
    else
        echo -e "${YELLOW}❖ Crontab tidak diaktifkan.${NC}"
        echo -e ""
    fi
}

# Jalankan fungsi enable_crontab
enable_crontab
