#!/bin/bash
# Mendefinisikan warna untuk pesan
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[0;33m'
BIRU='\033[0;34m'
PURPLE='\033[0;35m'
CYAN='\033[0;36m'
CYAN_BG='\033[46;1;97m'   # Latar belakang cyan cerah dengan teks putih
LIGHT='\033[0;37m'
PINK='\033[0;35m'
ORANGE='\033[38;5;208m'
PINK_BG='\033[45;1;97m'
BIRU_BG='\033[44;1;97m'
RED_BG='\033[41;1;97m'   # Latar belakang pink cerah dengan teks putih
NC='\033[0m'
INDIGO='\033[38;5;54m'
TEAL='\033[38;5;30m'
WHITE='\033[1;37m'
clear

function Loading_Succes() {
  clear

  # Karakter untuk animasi spinner
  spinner=( '|' '/' '-' '\' )

  # Simulasi animasi spinner
  for i in {1..3}; do
    for s in "${spinner[@]}"; do
      echo -ne "\r\033[1;33m[$s] Please wait... \033[0m"
      sleep 0.1
    done
  done

  # Tampilkan pesan sukses
  clear
  echo -e "\033[1;32m🎉 The process completed successfully! ✅\033[0m"
  sleep 1
  clear
}

  echo -e " ${TEAL}————————————————————————————————————${NC}"
  echo -e " ${PURPLE}      ❏ ADD BOT NOTIFIKASI ❏     ${NC}"
  echo -e " ${TEAL}————————————————————————————————————${NC}"    
echo ""
read -rp " ➽ YOUR BOT TOKEN  : " -e bottoken 
read -rp " ➽ YOUR CHAT ID    : " -e admin
echo -e ""
  echo -e " ${TEAL}————————————————————————————————————${NC}"    
clear
Loading_Succes


if [[ ${c} != "0" ]]; then
  echo "${d}" >/etc/bot/${bottoken}
fi
DATADB=$(cat /etc/bot/.bot.db | grep "^#bot#" | grep -w "${bottoken}" | awk '{print $2}')
if [[ "${DATADB}" != '' ]]; then
  sed -i "/\b${user}\b/d" /etc/bot/.bot.db
fi
echo "#bot# ${bottoken} ${admin}" >>/etc/bot/.bot.db

    echo -e " ${TEAL}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
    echo -e " ${PURPLE}       SETUP BOT SUCCESSFULLY    ${NC}"
    echo -e " ${TEAL}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}" 
    echo -e ""
    echo -e " ${WHITE} ➥ BOT TOKEN ${NC}: ${YELLOW}$bottoken ${NC} "
    echo -e " ${WHITE} ➥ ID CHAT    ${NC}: ${GREEN}$admin${NC} "
    echo -e ""
    echo -e " ${TEAL}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
    echo " "
    echo -e " ${TEAL}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
    echo -e " ${PURPLE}        Terimakasih Telah Menggunakan- ${NC}"
    echo -e " ${PURPLE} Script Credit By ROSI Store x SKT Project ${NC}"
    echo -e " ${TEAL}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
    echo ""