#!/bin/bash
# Mendefinisikan warna untuk pesan
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[0;33m'
BIRU='\033[0;34m'
PURPLE='\033[0;35m'
CYAN='\033[0;36m'
CYAN_BG='\033[46;1;97m'   # Latar belakang cyan cerah dengan teks putih
LIGHT='\033[0;37m'
PINK='\033[0;35m'
ORANGE='\033[38;5;208m'
PINK_BG='\033[45;1;97m'
BIRU_BG='\033[44;1;97m'
RED_BG='\033[41;1;97m'   # Latar belakang pink cerah dengan teks putih
NC='\033[0m'
INDIGO='\033[38;5;54m'
TEAL='\033[38;5;30m'
WHITE='\033[1;37m'
clear

UPDATE="https://abc.xcodehoster.com/"
BOT="https://abc.xcodehoster.com/"
ipsaya=$(curl -sS ipv4.icanhazip.com)
data_server=$(curl -v --insecure --silent https://google.com/ 2>&1 | grep Date | sed -e 's/< Date: //')
date_list=$(date +"%Y-%m-%d" -d "$data_server")
data_ip="https://raw.githubusercontent.com/Panwas89/1z1n/L1cense"
checking_sc() {
  useexp=$(wget -qO- $data_ip | grep $ipsaya | awk '{print $3}')
  if [[ $date_list < $useexp ]]; then
    echo -ne
  else
  echo -e " ${CYAN}======================================${NC}"
  echo -e " ${RED} TERTOLAK MENTAH MENTAH MAMPUS AWOKWOK ${NC}"
  echo -e " ${CYAN}======================================${NC}"
    echo -e ""
    echo -e "            ${RED}PERMISSION DENIED !${NC}"
    echo -e "   \033[0;33mYour VPS${NC} $ipsaya \033[0;33mHas been Banned${NC}"
    echo -e "     \033[0;33mBuy access permissions for scripts${NC}"
    echo -e "             \033[0;33mContact Admin :${NC}"
    echo -e "      ${GREEN}WhatsApp${NC} wa.me/"
  echo -e " ${CYAN}======================================${NC}"
    exit
  fi
}
checking_sc

  echo -e " ${CYAN}======================================${NC}"
  echo -e " ${PURPLE}      ❏ MENU BOT NOTIFICATION ❏ ${NC}" 
  echo -e " ${CYAN}======================================${NC}"
  echo -e " ${ORANGE}[1]${NC}${WHITE} Setup BOT Notifikasi${NC}"
  echo -e " ${ORANGE}[2]${NC}${WHITE} Remove BOT Notifikasi${NC}"
  echo -e " ${ORANGE}[x]${NC}${RED} Back To Menu${NC}"
  echo -e ""
  echo -e " ${CYAN}======================================${NC}"
read -p "  ➣ Your Choice: " menu
case $menu in
1) clear ;
    skt-bot-telegram-notif
    ;;
2) clear ;
    skt-bot-delete-notif
    ;;
x) clear ;
    menu
    ;;
*) clear ;
    menu
    ;;
esac
