#!/bin/bash

# Mendefinisikan warna untuk pesan
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[0;33m'
BIRU='\033[0;34m'
PURPLE='\033[0;35m'
CYAN='\033[0;36m'
CYAN_BG='\033[46;1;97m'   # Latar belakang cyan cerah dengan teks putih
LIGHT='\033[0;37m'
PINK='\033[0;35m'
ORANGE='\033[38;5;208m'
PINK_BG='\033[45;1;97m'
BIRU_BG='\033[44;1;97m'
RED_BG='\033[41;1;97m'   # Latar belakang pink cerah dengan teks putih
NC='\033[0m'
INDIGO='\033[38;5;54m'
TEAL='\033[38;5;30m'
WHITE='\033[1;37m'
clear

#Banner Ssh
  echo -e " ${CYAN}======================================${NC}"
  echo -e " ${RED_BG}             XRAY SERVICE            ${NC}"
  echo -e " ${CYAN}======================================${NC}"
  echo -e ""
  echo -e "  1.)  Check Usage Quota"
  echo -e "  2.)  List Member "
  echo -e " ${CYAN}======================================${NC}"
  echo -e " ${BIRU_BG}             XRAY TROJAN             ${NC}"
  echo -e " ${CYAN}======================================${NC}"
  echo -e "  3.)  Create Account Trojan"
  echo -e "  4.)  Trial Account Trojan"
  echo -e "  5.)  Delete Account Trojan"
  echo -e "  6.)  Renew Account Trojan"
  echo -e "  7.)  Check Config Account"
  echo -e "  8.)  Recovery Account"
  echo -e "  9.)  Edit Limit IP Account"
  echo -e "  10.) Edit Limit Bandwidth Account"
  echo -e "  11.) Lock Account"
  echo -e "  12.) Unlock Account"
  echo -e " ${CYAN}======================================${NC}"
  echo -e "  x.) Back to Menu"
  echo -e " "
  echo -e " ${CYAN}======================================${NC}"
  echo -e " "
read -p " ➣ Your Choice: " Ltt
case $Ltt in
1) clear ; tr -d '\r' < /usr/local/sbin/cek-tro > /tmp/fixed-script && mv /tmp/fixed-script /usr/local/sbin/cek-tro && chmod +x /usr/local/sbin/cek-tro && tr -d '\r' < /usr/local/sbin/sktaio-tro > /tmp/fixed-script && mv /tmp/fixed-script /usr/local/sbin/sktaio-tro && chmod +x /usr/local/sbin/sktaio-tro && cek-tro ;;
2) clear ; member-tro;;
3) clear ; add-tro ;;
4) clear ; trial-tro ;;
5) clear ; del-tro;;
6) clear ; renew-tro ;;
7) clear ; check-tro ;;
8) clear ; recover-tr ;;
9) clear ; ganti-ip-trojan ;;
10) clear ; trojan-qouta ;;
11) clear ; lock-tr ;;
12) clear ; unlock-tr ;;
x) clear ; menu ;;
*) sktaio-tro ;;
esac
