#!/bin/bash

# Mendefinisikan warna untuk pesan
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[0;33m'
BIRU='\033[0;34m'
PURPLE='\033[0;35m'
CYAN='\033[0;36m'
CYAN_BG='\033[46;1;97m'   # Latar belakang cyan cerah dengan teks putih
LIGHT='\033[0;37m'
PINK='\033[0;35m'
ORANGE='\033[38;5;208m'
PINK_BG='\033[45;1;97m'
BIRU_BG='\033[44;1;97m'
RED_BG='\033[41;1;97m'   # Latar belakang pink cerah dengan teks putih
NC='\033[0m'
INDIGO='\033[38;5;54m'
TEAL='\033[38;5;30m'
WHITE='\033[1;37m'
clear

#Banner Ssh
  echo -e " ${CYAN}======================================${NC}"
  echo -e " ${RED_BG}        SSH-Dropbear-Websocket       ${NC} "
  echo -e " ${CYAN}======================================${NC}"
  echo -e ""
  echo -e "  1.)  Check Users Login"
  echo -e "  2.)  Create Accounts"
  echo -e "  3.)  Delete Accounts"
  echo -e "  4.)  Renew Accounts"
  echo -e "  5.)  Trial Accounts"
  echo -e " ${CYAN}======================================${NC}"
  echo -e " ${BIRU_BG}               MEMBER                ${NC}"
  echo -e " ${CYAN}======================================${NC}"
  echo -e "  6.)  List Member Accounts"
  echo -e " ${CYAN}======================================${NC}"
  echo -e " ${BIRU_BG}            LOCK & UNLOCK            ${NC}"
  echo -e " ${CYAN}======================================${NC}"
  echo -e "  7.)  Lock Accounts"
  echo -e "  8.)  Unlock Accounts"
  echo -e " ${CYAN}======================================${NC}"
  echo -e " ${BIRU_BG}                LIMIT                ${NC}"
  echo -e " ${CYAN}======================================${NC}"
  echo -e "  9.) Edit Limit IP Account"
  echo -e "  10.) Limit IP On Off Accounts"
  echo -e " ${CYAN}======================================${NC}"
  echo -e "  x.) Back to Menu"
  echo -e " "
  echo -e " ${CYAN}======================================${NC}"
  echo -e " "
read -p " ➣ Your Choice: " Ltt
case $Ltt in
1) clear ; ceklim ;;
2) clear ; add-ssh ;;
3) clear ; del-ssh ;;
4) clear ; renew-ssh ;;
5) clear ; trial-ssh ;;
6) clear ; member-ssh ;;
7) clear ; lock ;;
8) clear ; unlock ;;
9) clear ; ganti-ip-ssh ;;
10) clear ; Lt-on-off ;;
x) clear ; menu ;;
*) sktaio-ssh ;;
esac
