#!/bin/bash
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[0;33m'
BIRU='\033[0;34m'
PURPLE='\033[0;35m'
CYAN='\033[0;36m'
CYAN_BG='\033[46;1;97m'   # Latar belakang cyan cerah dengan teks putih
LIGHT='\033[0;37m'
PINK='\033[0;35m'
ORANGE='\033[38;5;208m'
PINK_BG='\033[45;1;97m'
BIRU_BG='\033[44;1;97m'
RED_BG='\033[41;1;97m'   # Latar belakang pink cerah dengan teks putih
NC='\033[0m'
INDIGO='\033[38;5;54m'
TEAL='\033[38;5;30m'
WHITE='\033[1;37m'

# Getting
CHATID=$(grep -E "^#bot# " "/etc/bot/.bot.db" | cut -d ' ' -f 3)
KEY=$(grep -E "^#bot# " "/etc/bot/.bot.db" | cut -d ' ' -f 2)
export TIME="10"
export URL="https://api.telegram.org/bot$KEY/sendMessage"
ISP=$(curl -s ipinfo.io/org | cut -d " " -f 2-10 )
CITY=$(curl -s ipinfo.io/city )
domain=$(cat /etc/xray/domain)
nama=$(cat /etc/xray/username)
clear
IP=$(curl -sS ipv4.icanhazip.com)
Login=Trial-`</dev/urandom tr -dc X-Z0-9 | head -c4`
hari="1"
Pass=1
iplimit=99
#limitip
if [[ $iplimit -gt 0 ]]; then
mkdir -p /etc/saputratech/limit/ssh/ip/
echo -e "$iplimit" > /etc/saputratech/limit/ssh/ip/$Login
else
echo > /dev/null
fi
clear
ISP=$(cat /etc/xray/isp)
CITY=$(cat /etc/xray/city)
clear
tgl=$(date -d "$masaaktif days" +"%d")
bln=$(date -d "$masaaktif days" +"%b")
thn=$(date -d "$masaaktif days" +"%Y")
expe="$tgl $bln, $thn"
tgl2=$(date +"%d")
bln2=$(date +"%b")
thn2=$(date +"%Y")
tnggl="$tgl2 $bln2, $thn2"
useradd -e `date -d "$masaaktif days" +"%Y-%m-%d"` -s /bin/false -M $Login
exp="$(chage -l $Login | grep "Account expires" | awk -F": " '{print $2}')"
hariini=`date -d "0 days" +"%Y-%m-%d"`
expi=`date -d "$masaaktif days" +"%Y-%m-%d"`
echo -e "$Pass\n$Pass\n"|passwd $Login &> /dev/null
clear
  echo -e " ${CYAN}==============================${NC}"
  echo -e " ${PURPLE}    ❐ TRIAL SSH ACCOUNT ❐   ${NC}"
  echo -e " ${CYAN}==============================${NC}"
echo ""
read -p " Minutes : " pup
echo userdel ${Login} | at now + $pup minutes &> /dev/null
CHATID="$CHATID"
KEY="$KEY"
TIME="$TIME"
URL="$URL"
TEXT="
<code>————————————————————————————————————</code>
<code>    Trial SSH Account Created    </code>
<code>————————————————————————————————————</code>
<code>Host          : </code> <code>$domain</code>
<code>Username      : </code> <code>$Login</code>
<code>Password      : </code> <code>$Pass</code>
<code>Limit Device  : </code> <code>$iplimit</code>
<code>————————————————————————————————————</code>
<code>OpenSSH       : 443, 80, 22</code>
<code>Dropbear      : 443, 109</code>
<code>UDPGW         : 7100 - 7300</code>
<code>SSH UDP       : 1-65535 </code>
<code>SSH CDN WS    : 80, 8080, 8081-9999 </code>
<code>SSH CDN WSS   : 443</code>
<code>SSL/TLS       : 400-900</code>
<code>————————————————————————————————————</code>
<code>GET / HTTP/1.1[crlf]Host: [host][crlf]Upgrade: Websocket[crlf]Connection: Keep-Alive[crlf]Connection: Keep-Alive[crlf]User-Agent: [ua][crlf]Ping: clients3.google.com[crlf]Sec-WebSocket-Extensions: superspeed[crlf][crlf]</code>
<code>————————————————————————————————————</code>
<code>Expired On    : $pup Menit</code>
<code>————————————————————————————————————</code>
"

curl -s --max-time $TIME -d "chat_id=$CHATID&disable_web_page_preview=1&text=$TEXT&parse_mode=html" $URL >/dev/null

PAYLOADWS="GET / HTTP/1.1[crlf]Host: [host][crlf]Connection: Upgrade[crlf]User-Agent: [ua][crlf]Upgrade: websocket[crlf][crlf]"
clear


# Port Account Detail
echo -e "
 ————————————————————————————————————
     Trial SSH Account Created    
 ————————————————————————————————————
 Host          : $domain
 Username      : $Login
 Password      : $Pass
 Limit Device  : $iplimit
 ————————————————————————————————————
 OpenSSH       : 443, 80, 22
 Dropbear      : 443, 109
 UDPGW         : 7100 - 7300
 SSH UDP       : 1-65535
 SSH CDN WS    : 80, 8080, 8081, 9999
 SSH CDN WSS   : 443
 SSL/TLS       : 400-900
 ————————————————————————————————————
 ${PAYLOADWS}
 ————————————————————————————————————
  Expiry In  : ${pup} Minutes 
 ————————————————————————————————————
 "