#!/bin/bash

# Mendefinisikan warna untuk pesan
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[0;33m'
BIRU='\033[0;34m'
PURPLE='\033[0;35m'
CYAN='\033[0;36m'
CYAN_BG='\033[46;1;97m'   # Latar belakang cyan cerah dengan teks putih
LIGHT='\033[0;37m'
PINK='\033[0;35m'
ORANGE='\033[38;5;208m'
PINK_BG='\033[45;1;97m'
BIRU_BG='\033[44;1;97m'
RED_BG='\033[41;1;97m'   # Latar belakang pink cerah dengan teks putih
NC='\033[0m'
INDIGO='\033[38;5;54m'
TEAL='\033[38;5;30m'
WHITE='\033[1;37m'
nama=$(cat /etc/xray/username)
clear

function Loading_Succes() {
  clear

  # Karakter untuk animasi spinner
  spinner=( '|' '/' '-' '\' )

  # Simulasi animasi spinner
  for i in {1..3}; do
    for s in "${spinner[@]}"; do
      echo -ne "\r\033[1;33m[$s] Process Change Trojan Quota... \033[0m"
      sleep 0.1
    done
  done

  # Tampilkan pesan sukses
  clear
  echo -e "\033[1;32m🎉 The process completed successfully! ✅\033[0m"
  sleep 1
  clear
}
function Daftar_Account() {
grep -E "^#! " "/etc/xray/config.json" | cut -d ' ' -f 2-3 | column -t | sort | uniq
}

    echo -e " ${TEAL}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
    echo -e " ${PURPLE}            TROJAN QUOTA     ${NC}"
    echo -e " ${TEAL}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
    echo -e " ${TEAL}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"    
    grep -E "^#! " "/etc/xray/config.json" | cut -d ' ' -f 2-3 | sort | uniq | while read -r user exp; do
    printf "  %-28s %s\n" "$user" "$exp"  # Rata menggunakan printf
    done
    echo -e " ${TEAL}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}" 
    echo ""
	read -p " ➣ Input Username : " user
  quota_file="/etc/trojan/${user}"

  # Validasi apakah file kuota sudah ada
  if [ -e "$quota_file" ]; then
    current_quota=$(cat "$quota_file")
echo ""
    echo -e " ${TEAL}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo -e " ${PURPLE}            TROJAN QUOTA     ${NC}"
    echo -e " ${TEAL}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
    echo -e " ${TEAL}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"  
echo -e "${CYAN} BEFORE QUOTA ${NC}"    
echo -e ""  
echo -e " ${GREEN} Quota      : $((current_quota / 1024 / 1024 / 1024)) ${NC}"    
echo -e " ${GREEN} Username   : $user ${NC}"    
echo -e ""
    echo -e " ${TEAL}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo ""
read -p " Input New Quota (gb) : " new_quota
Loading_Succes

    # Validasi jika masukan kosong atau tidak valid
    if [[ -z "$new_quota" || ! "$new_quota" =~ ^[0-9]+$ ]]; then
      echo "Masukan tidak valid. Kuota tidak berubah."
    else

      # Konversi kuota ke byte
      new_quota_bytes=$((new_quota * 1024 * 1024 * 1024))
      echo "${new_quota_bytes}" > "${quota_file}"
    echo -e " ${TEAL}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
      echo -e " ${GREEN} Succesfully ${NC} "
      echo ""
      echo -e " ${CYAN} AFTER ${NC} "
      echo ""
      echo -e " ${WHITE} New Quota   : $new_quota GB ${NC} "
      echo -e " ${WHITE} Username    : $user ${NC} "
      echo ""
    echo -e " ${TEAL}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}" 

      # Hapus entri lama dan tambahkan yang baru ke dalam database
      DATADB=$(cat /etc/trojan/.trojan.db | grep "^#!" | grep -w "${user}" | awk '{print $2}')
      if [[ "${DATADB}" != '' ]]; then
        sed -i "/\b${user}\b/d" /etc/trojan/.trojan.db
      fi
      echo "#! ${user} ${exp} ${uuid} ${new_quota_bytes} ${iplimit}" >>/etc/trojan/.trojan.db
      
    echo -e " ${TEAL}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}" 
      echo " ${WHITE} Database Update Succes ${NC} "
    echo -e " ${TEAL}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
    fi
  else

  echo -e " ${TEAL}————————————————————————————————————${NC}"    
  echo ""
       echo -e "${RED} File kuota is Wrong Username :  $user ${NC} "
  Wecho ""
  echo -e " ${TEAL}————————————————————————————————————${NC}"    
  fi