#!/bin/bash
# Lt
# ==========================================
# Color
RED='\033[0;31m'
NC='\033[0m'
GREEN='\033[0;32m'
ORANGE='\033[0;33m'
BLUE='\033[0;34m'
PURPLE='\033[0;35m'
CYAN='\033[0;36m'
LIGHT='\033[0;37m'
BlueCyan='\e[5;36m'
Xark='\e[0m'
ungu='\033[35m'
yellow='\e[33m'
WhiteBe='\e[5;37m'
GreenBe='\e[5;32m'
BlueCyan='\e[5;36m'
White="\033[97;1m"
Green="\033[92;1m"
Cyan="\033[96;1m"
Xark='\e[0m'
# ==========================================
# // Get Bot
CHATID=$(grep -E "^#bot# " "/etc/bot/.bot.db" | cut -d ' ' -f 3)
KEY=$(grep -E "^#bot# " "/etc/bot/.bot.db" | cut -d ' ' -f 2)
export TIME="10"
export URL="https://api.telegram.org/bot$KEY/sendMessage"
# Getting
MYIP=$(curl -sS ipv4.icanhazip.com);
nama=$(cat /etc/xray/username)
ISP=$(cat /etc/xray/isp)
CITY=$(cat /etc/xray/city)
domain=$(cat /etc/xray/domain)

clear
echo -e "\033[5;36m┌──────────────────────────────────────────┐\033[0m"
echo "   USERNAME       EXP DATE         STATUS"
echo -e "\033[5;36m└──────────────────────────────────────────┘\033[0m"
echo -e "\033[5;36m┌──────────────────────────────────────────┐\033[0m"
while read expired
do
AKUN="$(echo $expired | cut -d: -f1)"
ID="$(echo $expired | grep -v nobody | cut -d: -f3)"
exp="$(chage -l $AKUN | grep "Account expires" | awk -F": " '{print $2}')"
status="$(passwd -S $AKUN | awk '{print $2}' )"
if [[ $ID -ge 1000 ]]; then
if [[ "$status" = "L" ]]; then
 printf "%-17s %2s %-17s %2s \n" "  $AKUN" "$exp   " "LOCKED${NORMAL}"
else
 printf "%-17s %2s %-17s %2s \n" "  $AKUN" "$exp   " "UNLOCKED${NORMAL}"
fi
fi
done < /etc/passwd
echo -e "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo -e " Masukan Username Account SSH"
read -rp "Input Username : " user
if [ -z $user ]; then
echo -e "User Tidak Ditemukan!!!"
read -n 1 -s -r -p "Enter Back To Menu"
sktaio-ssh
else
sleep 2 & loading $!
echo -e "\033[0m"

Login=$(cat /etc/ssh/.ssh.db | grep -wE $user | awk '{print $2}')
Pass=$(cat /etc/ssh/.ssh.db | grep -wE $user | awk '{print $3}')
Quota=$(cat /etc/ssh/.ssh.db | grep -wE $user | awk '{print $4}')
iplimit=$(cat /etc/ssh/.ssh.db | grep -wE $user | awk '{print $5}')
expe=$(cat /etc/ssh/.ssh.db | grep -wE $user | awk '{print $6" "$7" "$8}')

PAYLOADWS="GET / HTTP/1.1[crlf]Host: [host][crlf]Connection: Upgrade[crlf]User-Agent: [ua][crlf]Upgrade: websocket[crlf][crlf]"

CHATID="$CHATID"
KEY="$KEY"
TIME="$TIME"
URL="$URL"
TEXT="
<code>————————————————————————————————————</code>
<code>    Trial SSH Account Created    </code>
<code>————————————————————————————————————</code>
<code>Host          : </code> <code>$domain</code>
<code>Username      : </code> <code>$Login</code>
<code>Password      : </code> <code>$Pass</code>
<code>Limit Device  : </code> <code>$iplimit</code>
<code>————————————————————————————————————</code>
<code>OpenSSH       : 443, 80, 22</code>
<code>Dropbear      : 443, 109</code>
<code>UDPGW         : 7100 - 7300</code>
<code>SSH UDP       : 1-65535 </code>
<code>SSH CDN WS    : 80, 8080, 8081-9999 </code>
<code>SSH CDN WSS   : 443</code>
<code>SSL/TLS       : 400-900</code>
<code>————————————————————————————————————</code>
<code>GET / HTTP/1.1[crlf]Host: [host][crlf]Upgrade: Websocket[crlf]Connection: Keep-Alive[crlf]Connection: Keep-Alive[crlf]User-Agent: [ua][crlf]Ping: clients3.google.com[crlf]Sec-WebSocket-Extensions: superspeed[crlf][crlf]</code>
<code>————————————————————————————————————</code>
<code>Expired On    : $expe</code>
<code>————————————————————————————————————</code>
"
curl -s --max-time $TIME -d "chat_id=$CHATID&disable_web_page_preview=1&text=$TEXT&parse_mode=html" $URL >/dev/null


# Details ACcount
f# Port Account Detail
echo -e "
 ————————————————————————————————————
     Trial SSH Account Created    
 ————————————————————————————————————
 Host          : $domain
 Username      : $Login
 Password      : $Pass
 Limit Device  : $iplimit
 ————————————————————————————————————
 OpenSSH       : 443, 80, 22
 Dropbear      : 443, 109
 UDPGW         : 7100 - 7300
 SSH UDP       : 1-65535
 SSH CDN WS    : 80, 8080, 8081, 9999
 SSH CDN WSS   : 443
 SSL/TLS       : 400-900
 ————————————————————————————————————
 ${PAYLOADWS}
 ————————————————————————————————————
  Expiry In  : $expe 
 ————————————————————————————————————
 "
read -n 1 -s -r -p "Enter Back To Menu"
sktaio-ssh
fi